### ISSUE TITLE
Add pocl to VMware Ubuntu CMake

### ISSUE THREAD

**Issue by FTamas77** [pocl/pocl#1022]
Is there any easy way to do this? I did research on the internet, but I cannot do it.
Doesn't it support OpenCL 3.0?

**Comment by MathiasMagnus** [comment]
@FTamas77 The issue title and your question(s) are in total disconnect. Please be a little more specific on what you want to achieve.

Judging by [the issue](https://github.com/FTamas77/parallelCompApp/issues/2) opened slightly sooner on your own repo you're trying to get a GPU device accelerated OpenCL app to run using POCL on an Nvidia GPU. The POCL team can do little to make that happen, and "Adding POCL to VMware Ubuntu CMake" is nondescript. Your issue is that VMware virtualizes the HW and POCL can only interact with Nvidia devices as long as CUDA acceleration is available. (The POCL runtime will utilize CUDA to load/launch kernels and transfer data.) I'm not aware as to how that can be done, but you should research on how to get CUDA accel inside a VMWare Linux guest.
