### ISSUE TITLE
`getPointerElementType` got deprecated in LLVM 15

### ISSUE THREAD

**Issue by KOLANICH** [pocl/pocl#1060]
`'getPointerElementType' is deprecated: Deprecated without replacement, see https://llvm.org/docs/OpaquePointers.html for context and migration instructions`

**Comment by dnsampaio** [comment]
LLVM15 deprecates typed pointers to use opaque pointers as default. I've fixed this issue by using getArrayElementType, but even if pocl compiles all pointer treatments are broken. I was trying to make llvm 15 behave as llvm 14 in this regard. See
https://llvm.org/docs/OpaquePointers.html

"For users of LLVM as a library, opaque pointers can be disabled by calling setOpaquePointers(false) on the LLVMContext."
But I still couldn't find where to do that in pocl. Could someone provide some insight about it?

**Comment by franz** [comment]
@dnsampaio  the relevant code is in `lib/CL/pocl_llvm_utils.cc`, function `pocl_llvm_create_context`. It'd be preferable to use the LLVM C API (`LLVMContextSetOpaquePointers()`) instead of the C++ API, but in this case it likely doesn't matter, as we'll have to do the transition to opaque pointers by LLVM 16 at latest.

**Comment by franz** [comment]
LLVM 15 is now supported.

**Comment by KOLANICH** [comment]
🎉
