### ISSUE TITLE
Question about a warning (probably related to LLVM)

### ISSUE THREAD

**Issue by kif** [pocl/pocl#1324]
This is not really an issue, it is just that I do not understand this warning  generated by PoCL on device `pthread-haswell-Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz`:
```
AVX vector argument of type '__private float16' (vector of 16 'float' values) without 'avx512f' enabled changes the ABI
```

The processor does not support AVX512 but PoCL should not expect it since AVX512 has never been available on the Haswell architecture.

Does this  warning deserve to be fixed in my code ?

**Comment by pjaaskel** [comment]
Shouldn't be an issue if your code runs fine, but should be worth investigating if we pass some wrong machine options somewhere. But then your code should not run fine.

**Comment by franz** [comment]
IIRC I've seen this warning also on 128bit vector CPUs using 256bit (and larger) vectors. My understanding is that this warning is generated when source code uses Clang's "extended vector" larger than can fit into the largest CPU register as function argument (PoCL uses Clang extended vectors internally to implement OpenCL vectors). I suspect the warning that it "changes the ABI" is probably because there isn't any official way in the x86-64 ABI specification to pass vector-larger-than-AVX-register as function argument, so Clang has to come up with its own "creative" way and it's no the longer strictly following the official ABI. AFAIK there is only one place in PoCL where this is currently a problem, in the `printf()` function, likely related to varargs (issue #1017). In code that doesn't use varargs, this should not be a problem, our CI tests 512bit vectors on 256bit x86 and 128bit ARM machines.
