### ISSUE TITLE
Kernel execution fails with SIGBUS (Misaligned address error)

### ISSUE THREAD

**Issue by fjarri** [pocl/pocl#1525]
MacOS 14.5, pocl 6.0 (installed via homebrew)

`kernel.cl`: https://gist.github.com/fjarri/f86652b38cc61969d0c7933ad3f27d36
`test.c`: https://gist.github.com/fjarri/7f8fb6de256bba5292044807a64dc825
(sorry for the sloppy C code, the example was reduced to MRE from a large Python codebase)
```
$ gcc test.c -lpocl -L/opt/homebrew/Cellar/pocl/6.0/lib`
$ /a.out
Platform: Portable Computing Language
Device: cpu
Before synchronizing the queue
fish: Job 1, './a.out' terminated by signal SIGBUS (Misaligned address error)
``` 

As far as I understand, the kernel should simply copy `input` into `output`. All the memory accesses are within the buffer ranges. The kernel works as expected if:
- one removes the local mem barrier (even though local mem is not even used)
- explicit `local_work_size` when invoking the kernel is substituted with `NULL` (that is, if the local work size choice is automatic)
- `local_work_size` and `global_work_sze` are less than 1024+512. 
- the unrolled memory loads/saves are substituted with loops

**Comment by pjaaskel** [comment]
Due to the barrier PoCL generates a lot of context data, for each of the compute i increment, in addition to the user array, which leads to large stack consumption. On MacOS the stack is limited to 640KB (? pls verify with 'ulimit -s') which easily gets exhausted by this case.

```
pjaaskel@pjaaskel-mobl1:~/src/pocl/build-cpu$ ulimit -s 640
pjaaskel@pjaaskel-mobl1:~/src/pocl/build-cpu$ tests/regression/test_issue_1525
Segmentation fault
```
Works here otherwise (Linux, x86, LLVM 17). Where did you get that 'Misaligned address error' from? It would hint towards unaligned access, but who knows what exhausting the stack could cause...

The correct fix would be to return CL_OUT_OF_RESOURCES from clEnqueueNDRangeKernel() when detecting the stack will exceed the process limit: _"CL_OUT_OF_RESOURCES if there is a failure to queue the execution instance of kernel on the command-queue because of insufficient resources needed to execute the kernel. For example, the explicitly specified local_work_size causes a failure to execute the kernel because of insufficient resources such as registers or local memory."_

The need for stack could be reduced via rematerialization, if seen important. If you are interested in implementing that, let me know and I can give hints. Converting the allocas to mallocs could cause loss of alignment or info of it, which is necessary for vectorization for some ISAs.

**Comment by fjarri** [comment]
> pls verify with 'ulimit -s'

It reports 8176 kb. 

> Where did you get that 'Misaligned address error' from?

That's what shows in the console along with the error (see the console output in the starting message). I don't know exactly where that message originates from. 

> The correct fix would be to return CL_OUT_OF_RESOURCES from clEnqueueNDRangeKernel() when detecting the stack will exceed the process limit

That would work great for me, I already have a fallback system that gradually reduces local size if CL_OUT_OF_RESOURCES is returned.

**Comment by fjarri** [comment]
I tried to set the stack size to 65536, didn't change the outcome.

**Comment by franz** [comment]
@fjarri  according to my [search](https://github.com/libuv/libuv/issues/669) the stack size on Mac OS X is 8MB for the *main* thread, all other threads are then limited to 512KB. However, that issue is quite old, so maybe the limits are different now. Can you try running the test with `POCL_DEVICES=cpu-minimal` env variable ? The cpu-minimal device does not create any new threads, it executes everything in the main thread.

**Comment by fjarri** [comment]
It does work with `cpu-minimal`.

**Comment by pjaaskel** [comment]
@fjarri: interesting. Then what @franz commented could be an explanation here since cpu-minimal doesn't use child threads.

**Comment by franz** [comment]
There two workarounds available now. First, the default WG size of the CPU device was lowered to 4096 (users can lower it further by an env var), and second: there is a CMake option `HOST_CPU_ENABLE_STACK_SIZE_CHECK` which calculates a worst-case stack size for each kernel and limits both the user-provided `local_work_size` to `clEnqueueNDRangeKernel()` and the automatic size (when `local_work_size` is NULL). The size can be queried using `clGetKernelWorkGroupInfo(..., CL_KERNEL_WORK_GROUP_SIZE, ...)`. This option is disabled by default though, as the worst case is often too pessimistic.

**Comment by pjaaskel** [comment]
Please check if it now works for you and reopen if not.

**Comment by pjaaskel** [comment]
In the next release which will be tagged 6.1 or 7.0 (we haven't decided yet). But meanwhile you can test with the main branch which is stable.
