### ISSUE TITLE
modf results in undefined symbol error

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#198]
Running this kernel

```opencl
__kernel void modf_kernel(__global float *intpart__base, long intpart__offset, __global float *fracpart__base, long fracpart__offset, __global float *x__base, long x__offset, long n)
{
  int lid = get_local_id(0);
  int gsize = get_global_size(0);
  int work_group_start = get_local_size(0)*get_group_id(0);
  long i;

  __global float *intpart = (__global float *) ((__global char *) intpart__base + intpart__offset);
  __global float *fracpart = (__global float *) ((__global char *) fracpart__base + fracpart__offset);
  __global float *x = (__global float *) ((__global char *) x__base + x__offset);;

  for (i = work_group_start + lid; i < n; i += gsize)
  {
    fracpart[i] = modf(x[i], &intpart[i]);
  }
}
```

results in

```
/home/andreas/.pocl/kcache/LL/MMCFLEHGDEIPCGIOKFIHFMEKOBDEGKADEDFJP/modf_kernel/32-1-1/modf_kernel.so: undefined symbol: _cl_modf
```

(and a program abort) for me. 

(Low priority as far as I'm concerned. Just figured I'd report it.)

**Comment by inducer** [comment]
(same for `frexp`)

**Comment by pjaaskel** [comment]
This is likely just an unimplemented builtin, right @eschnett ?

**Comment by eschnett** [comment]
`modf` and `frexp` are both implemented in vecmathlib. I don't see a non-vecmathlib implementation. How did you configure pocl? Can you check whether vecmathlib is enabled?

**Comment by pjaaskel** [comment]
It might be a name mangling issue. The "missing symbol" is a C mangled symbol although the library functions are mangled.

**Comment by pjaaskel** [comment]
_kernel.h seems to miss declarations (which have the override attributes) for these functions, am I correct? Any idea why? The names are in comments in this file.

**Comment by eschnett** [comment]
The names are in comments probably because these functions were implemented later than the others; the comments served as reminder that they were still missing. In other words, they should likely be un-commented.

**Comment by inducer** [comment]
I was poking around trying to fix this, but I found something I don't understand: Some of the declaration macros do declare non-vector versions (as in, just plain "double" or "float") of their functions, and some do not. For instance, compare `_CL_DECLARE_FUNC_V_VPV` (does) vs `_CL_DECLARE_FUNC_V_VI` (does not). Which one is the right thing to do for modf and frexp? Or is this a bug?

Compare:
* https://github.com/pocl/pocl/blob/master/include/_kernel.h#L816
* https://github.com/pocl/pocl/blob/master/include/_kernel.h#L798

**Comment by eschnett** [comment]
Welcome to OpenCL's library APIs. They are not very self-consistent.

In general, if there is a library function that takes several `int` arguments, then it exists also in a version that takes several `long` arguments, as well as versions that take respective vector arguments. However, the scalar versions often have exceptions, e.g. when vector functions accept `double` and `long` arguments, the scalar version would accept a `double` and an `int` argument. There seem to be some rules of thumb, and the macros try to follow them. However, as you notice, all in all it's rather messy, and using just a few characters to encode the API of a library function is not really possible. Hence all the exceptions. In general, the floating-point macros also follow slightly different conventions than the integer macros.

I think these C macros should be replaced by Python-generated code. That may (or may not) also speed up compile time. A more "modern" set of definitions is found e.g. in `lib/kernel/vecmathlib-pocl/generate-files.py`, but this doesn't generate pocl's `_kernel.h` file (yet?). Currently, it's mostly lack of momentum that is preventing such a change.

In the case you mention, the inconsistency is due to a conflict. The respective scalar definition is omitted to avoid declaring things twice. There is `ldexp(floatN, intN)` as well as `ldexp(floatN, int)` (no `N` after `int`). The macro `_V_VJ` handles the first case, which also handles the scalar case (equivalent to N=1). The macro `_V_VI` handles the second case, and the scalar version is then omitted to avoid declaring `ldexp(float, int)` twice.

Having said this -- I think `_V_VPV` is the way to go; it is e.g. already used for `fract` or `sincos`.

**Comment by eschnett** [comment]
`_V_VPV` should be used for `modf`. `frexp` should use `_V_VPK`, which doesn't exist yet. This needs to include the scalar version as well.

**Comment by inducer** [comment]
Tried this:

https://gist.github.com/inducer/6b177a4aedf042c07c0c

Didn't change a thing. (Which makes some sense--it's a missing symbol after all, not a missing declaration...)

**Comment by eschnett** [comment]
Okay, back to the beginning. Can you look at your configure output to see whether vecmathlib (VML) is enabled?

**Comment by inducer** [comment]
This is what it says at the end:

```
Using LLVM version 3.6.1 from /usr/lib/llvm-3.6

ICD extension: enabled
Using ocl-icd to run checks inside build tree.

Enabling direct linking with libpocl.

Using vecmathlib math builtins.
Enabled device drivers: basic pthreads
Enabled testsuites: viennacl
NOTE: Initialize the examples used by the testsuites by running
"make prepare-examples" once.

Basic and pthreads devices optimized for:
architecture: x86_64
cpu variant: x86-64
```

So it seems vecmathlib is enabled.

**Comment by pjaaskel** [comment]
It must still miss the overloadable declaration, otherwise it would not miss an unmangled function. The compiler assumes C mangling if it doesn't see the overloadable declaration because in C declarations are optional Try cleaning or disabling your kcache, maybe it hits your old artifacts.

**Comment by inducer** [comment]
Same after `rm -Rf ~/.pocl ` (and clearing PyOpenCL's cache, too).

**Comment by pjaaskel** [comment]
Your patch does fix the missing frexp issue for me. Are you sure you are using the correct _kernel.h? Are you using an installed version which might not have the latest version installed? This might be useful: http://portablecl.org/docs/html/development.html#using-pocl-from-the-build-tree

**Comment by pjaaskel** [comment]
modf seems to miss versions with integer as the 2nd parameter..

**Comment by eschnett** [comment]
I don't think these should exist. The OpenCL specification speaks of `gentype`, which is defined to be `float`, `double`, or `half` only.

**Comment by inducer** [comment]
I am using `make install` after every change, and the correct `_kernel.h` seems to be put in place.

**Comment by pjaaskel** [comment]
@eschnett true. So @inducer's example is just wrong as modf expects a gentype as the 2nd argument and there should not be an int version. After inducer's patch this works for me (I'll commit after adding to the testsuite):

```OpenCL
kernel
void test_frexp_modf() {
    volatile float a = 1.5f, frac;
    int exp;
    frac = frexp(a, &exp);
    printf("frexp(1.5f): %.1f %d\n", frac, exp);
    float x;
    frac = modf(a, &x);
    printf("modf(1.5f): %.1f %1f\n", frac, x);
}
```

**Comment by eschnett** [comment]
@pjaaskel The example given in this issue (in the very beginning) is correct -- it uses `float*`.

**Comment by pjaaskel** [comment]
@eschnett Ah true, but with a double reference so the passed arg is float**?

**Comment by pjaaskel** [comment]
Ah no, didn't notice the array brackets. Hmmh.

**Comment by pjaaskel** [comment]
I believe this is now fixed. If it still doesn't work, pls check that lib/kernel/host is rebuilt. The build system doesn't follow _kernel.h changes properly there.

**Comment by inducer** [comment]
Sorry, stale (PyOpenCL) cache on my end. Works now. Thanks for your help!
