### ISSUE TITLE
wrongly detected cpu variant for AMD FX(tm)-6300 when ran inside a VM guest

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#268]
See https://github.com/pocl/pocl/issues/181#issuecomment-148221927

**Comment by pjaaskel** [comment]
Because we use LLVM (llc) to detect the CPU variant, we probably cannot fix this cleanly in pocl. But let's take a look.

**Comment by pjaaskel** [comment]
@gerddie does clang fail when compiling a hello world or similar? If it's an llc issue like it seems, it probably affects also clang compilation, and should be reported to LLVM.

**Comment by gerddie** [comment]
Clang doesn't fail compiling things within the VM and I don't think clang wrongly detects the CPU type. As I wrote in #181, within the VM linux reports different CPU flags, i.e. 

     flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx 
       fxsr sse sse2 ht syscall nx fxsr_opt rdtscp lm rep_good nopl extd_apicid pni ssse3 
       lahf_lm cmp _legacy cr8_legacy 3dnowprefetch arat vmmcall

whereas outside it is 

    flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush 
       mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc 
       rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma 
       cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic 
       cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 
       tce nodeid_msr tbm topoext perfctr_core perfctr_nb arat cpb hw_pstate npt lbrv
       svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter 
       pfthreshold vmmcall bmi1

I guess that has something to do with what VirtualBox is capable of (I'm running 4.3.28). In addition two of the the tests failed also on my Laptop where I have a Intel Core 2 Duo (penryn, as reported) that reports flags: 

    flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts 
     acpi mmx  fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts 
     rep_good nopl aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm sse4_1 
     xsave lahf_lm dtherm

**Comment by pjaaskel** [comment]
It looks very much like a llc issue, but I don't have neither CPUs at hand for checking it. I used to have a Core 2 Duo machine, but not anymore. Can you provide shell access to these? 

Do you have the same problems with pocl 0.11? We are currently considering only regressions can block the (already late) 0.12 release.

**Comment by gerddie** [comment]
Well, I didn't try 0.11 on the Core2 machine, but I'm quite certain that the problem arose in the VM, because I came across it when looking into packaging 0.11 for Debian. I can check this tomorrow. 

Considering shell access - that's going to be difficult since I'm on dynamic IP's, and - no offence - but I'm also a bit reluctant to give out shell access to a private computer to someone I never met in person and can not confirm the identity. For the latter there is one option though: if you have a PGP key that is signed by trustworthy, e.g a Debian Developer, that would certainly be helpful.  Incidentally, there is a DD in Tampere: David Weinhall.   https://www.linkedin.com/pub/david-weinehall/3/304/734
My keys fingerprint is: 4587 7F1F 6F59 1AB1 F366  BC3A 0254 1A37 1530 B71F

**Comment by pjaaskel** [comment]
I understand. No offence taken. I should really start using the PGP key I've generated one of this days.

But since this is likely a llc issue (we use llc for detecting CPU features in configure) and also probably not a regression, removing the tag 0.12 for now.  Please comment if you think othwerise.

**Comment by gerddie** [comment]
I don't have any objections about removing the 0.12 tag, but I'd like to point out that a Core2 Duo is a penryn, so llc is reporting the right thing there. 

After reviewing the cpuflags for bdver1 I can imagine that there are problems within the VM, because the reported flags do not cover what bdver1 actually supports. I'm a bit surprise now, that things worked that I compiled with -mcpu=native, I should check that again with some more demanding code. 

Two other things I tried was setting LLC_HOST_CPU to

* bdver1 on bdver2 outside the VM and all tests passed. 
* x86-64 on bdver2 outside the VM and all tests passed. 
* x86-64 on bdver2 inside the VM that reports bdver1 and tests 26 and 27 failed with the same errors like before. 
* x86-64 on penryn and tests 26 and 27 failed with the same errors

**Comment by pjaaskel** [comment]
Might be related: https://llvm.org/bugs/show_bug.cgi?id=25021#c7

**Comment by gerddie** [comment]
On penryn I get the same test failures with llvm-3.6 and cpuflags reports ssa4_1. I think if the code generation failed because of detecting the wrong cpu, then it should issue an "illegal instruction" failure, but the tests simply fail because some functions return the wrong value (also in the VM).

**Comment by pjaaskel** [comment]
Not necessarily. I've seen before (in fact on Core 2) an issue that was triggered by a (miscompilation) bug when generating for a certain variant of SSE/MMX and which wasn't there when generating for a newer variant.

**Comment by gerddie** [comment]
I see, but the LLVM bug explicitely mentions "illegal instruction" .. 

Is there a way to see easily see the assembly of the code pocl created for an opencl kernel?

**Comment by pjaaskel** [comment]
Yes. Check http://portablecl.org/docs/html/env_variables.html especially POCL_CACHE_DIR and POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES. Then run your program and check the files it produces. There are multiple LLVM bitcode versions and the final parallel.so which you can objdump.

**Comment by pjaaskel** [comment]
This is likely fixed with later LLVM's or pocl, please try, and if not, reopen.
