### ISSUE TITLE
armv7hl support

### ISSUE THREAD

**Issue by ignatenkobrain** [pocl/pocl#275]
Hi, do we support armv7hl? Because most of tests fails there: https://kojipkgs.fedoraproject.org//work/tasks/8952/11718952/build.log.

**Comment by franz** [comment]
We support whatever clang supports.

I'm guessing armv7hl equals "armv7 hard-float little-endian" in which case it should work. But it might mean something else, i've always found the arm target/triple strings to be a highly confusing mess...  configure.ac has a bit of "sanitization" code (because clang has a different target/triple mess than your autotools), you might need to tweak that.

But the fails might also be caused by different reasons, hard to tell without the log.

BTW we have tested pocl on Odroids (U3 & XU3), cubieboard, RPi and some others i can't remember...

**Comment by franz** [comment]
Forgot to say, you'll find the failure details in "tests/testsuite.log"

**Comment by kraiskil** [comment]
I wonder if autotest could be coaxed to print out a failing test's log to stdout when running 'make check'. This "hiding" of the pertinent details seems to bite quite frequently.

**Comment by pjaaskel** [comment]
Needs more info.
