### ISSUE TITLE
LLVM AMD GPU

### ISSUE THREAD

**Issue by jsteube** [pocl/pocl#291]
Not an issue, just a question:

While I was compiling LLVM 3.7 from source I saw that it ships with a target called "AMD GPU". I'm not really sure what this means but it came into my mind that it maybe means that pocl can use this target to execute OpenCL kernel on AMD GPUS? 

That would be really nice as an OSS alternative to Catalyst!

Or the question in general is, does pocl aim to execute code on GPU as well?

**Comment by franz** [comment]
You mean LLVM's lib/Target/AMDGPU ? Yes that is LLVM's AMD GPU backend. However pocl can't use AMD GPUs that easily - while LLVM can compile C/C++/OpenCL into binaries that run on GPUs, that's not enough to do anything useful. You need infrastructure that deals with gpu memory, submits commands to the gpu processor, and similar (rather low-level) stuff. Pocl doesn't have any of this.

However, this infrastructure exists already, in Mesa libraries. So to get an OSS OpenCL with AMD GPUs all you need to do is install "mesa-opencl" or similarly named package on your system. A lot of stuff is still unimplemented, but for something relatively simple like password-hashing it might actually be worth a try.

**Comment by franz** [comment]
Forgot to say

> Or the question in general is, does pocl aim to execute code on GPU as well?

We have some support for GPU on APUs, specifically AMD Kaveri and Carrizo. [Details here](http://portablecl.org/docs/html/hsa.html) It's quite cumbersome to get running, some parts are unimplemented, but basic things work. This is something we're actively working on these days.

I don't see pocl supporting discrete GPUs anytime soon - it'd be huge amount of work, and the Mesa folks have already done quite a big part of it.

**Comment by jsteube** [comment]
Thanks for clarify

**Comment by pjaaskel** [comment]
I suppose you missed my advertisement in https://github.com/hashcat/oclHashcat/issues/3 

To clarify a bit @franz's comments is that have experimental support for HSA and via that some AMD GPUs, and hopefully in the future even more different HSA supported devices. We appreciate testing and comments, but there are known performance issues related to the LLVM-HSA. 

Initial native GPU support for AMDGPUs used to be there actually (using the HSA Runtime API and the LLVM's AMDGPU backend), but it's not currently maintained due to focusing on HSA. It will be interesting to perhaps re-add support also for the direct AMDGCN target for comparison purposes at some point.
