### ISSUE TITLE
implement mem_fence()

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#294]
https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/mem_fence.html

**Comment by franz** [comment]
Fixed in 69c5b9060dcd361f995812a09e47684215d6e5dc

**Comment by Oblomov** [comment]
I'm not sure an empty implementation will work. The purpose of `mem_fence` instructions is to ensure that instructions are not reordered across the fence. If the compiler optimizes out the empty function call, there is nothing preventing this from happening, is there?

**Comment by pjaaskel** [comment]
I think it should work for currently supported CPUs due to how WIs are handled in pocl (converted to loops basically), thus the loads/stores will be in the same thread and program ordering should enforce the desired ordering without explicit fence instructions. If you think I might be wrong, please elaborate.

**Comment by pjaaskel** [comment]
After writing that I realized that perhaps WIs from different WGs might still require explicit fences in place. This needs more checking.

**Comment by Oblomov** [comment]
I think that at least a cache flush in the CLK_GLOBAL_MEM_FENCE case is needed. For the local case, I'm not entirely sure that no action is needed, since the compiler might reorder across the fence, which might mess up things subtly in cases (I remember reading about someone complaining about some CPU OpenCL platform implementations basically reordering across atomics due to lack of proper fencing).

**Comment by pjaaskel** [comment]
I think compiler should not mess it up unless there is a WaW to different addresses which the compiler of course cannot know have some relation (there might be basically I/O or control register ordering restriction of some kind). For that, yes, a compiler barrier might be helpful. Across threads it is indeed a different story, so it would be better use some suitable Clang/LLVM builtin here instead or in addition to a simple compiler barrier.
