### ISSUE TITLE
cannot find -ledit

### ISSUE THREAD

**Issue by ghost** [pocl/pocl#295]
I'm trying to install pocl on an ODROID-XU3 using the ARM Cortex A15 2.0Ghz quad care and Cortex A7 quad core. I'm using Ubuntu 15.04.

I have downloaded and extracted pocl, ran ./autogen.sh, then ./configure. When I run make i get the following error:

/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status

**Comment by pjaaskel** [comment]
Hard to say from this only. pocl should not -ledit. Can you put config.log somewhere?

**Comment by franz** [comment]
pocl doesn't need libedit; most likely you downloaded LLVM/clang which is linked to libedit. You need to find & install whatever the required libraries are for LLVM on your machine (on Ubuntu, probably libedit-dev or something like that).

**Comment by Grailixir** [comment]
Thank you, I had looked for llvm/clang requirements but libedit wasn't on there. Running sudo apt-get install libedit-dev worked though.

I'm now running into a problem of being unable to find clang/CodeGen/CodeGenAction.h for pocl_llvm_api.cc.

I have attached my config.log if that helps.


[config.txt](https://github.com/pocl/pocl/files/105380/config.txt)

**Comment by franz** [comment]
well, do you have that file ? if you downloaded clang from llvm.org, it should be somewhere in `<llvm-unpacked-dir>/include/clang/CodeGen/CodeGenAction.h`

If im not mistaken, your config.log says you run ./configure without any options and it picked up your system llvm, which is most likely not what you want ?

So to be clear, 
* if you want pocl to use system llvm, you must install clang & llvm headers and develoment files for your distro
* if you want pocl to use some downloaded / built llvm, you must run `./configure LLVM_CONFIG=<path-to-llvm-config>`

**Comment by Oblomov** [comment]
For what it's worth, this also happens when using Debian's own llvm packages, both versioned and unversioned ones: llvm depends on libedit, `-ledit` is reported as system library needed for linking, but the `-dev` packages don't depend on `libedit-dev`. This is [a known issue in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792842).

It might be worth checking that linking with the required libraries actually works at configuration time, and warn the users if things fail.

**Comment by franz** [comment]
Link check in place.
