### ISSUE TITLE
build broken with gcc 6.1

### ISSUE THREAD

**Issue by mnhauke** [pocl/pocl#357]
openSUSE factory is currently switching the whole distribution to gcc6.1
The vecmathlib version that's shipped with pocl 0.13 actually fails to build with gcc6.1 ...

[pocl-0.13-gcc61-vemathlib-broken.txt](https://github.com/pocl/pocl/files/322279/pocl-0.13-gcc61-vemathlib-broken.txt)

**Comment by franz** [comment]
The problem is, clang uses gnu stdlib headers, which are part of gcc (AFAIK) and they changed several things from macros to non-macros.

The vecmathlib code has ``#if C++11 ... else redefine-macros`` and it hits the else branch because clang defaults to C++98. @visit0r  do you think we can add -std=c++11 for vecmathlib's c++ code ? idk how clang 3.7+ supports c++11 but i imagine its good enough for us ?
