### ISSUE TITLE
don't put fullpath into .icd

### ISSUE THREAD

**Issue by ignatenkobrain** [pocl/pocl#369]
OpenCL ICD specification supports just library name without full path (it's anyway bad idea to put full library path into `/etc`)

See also: https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/targets/opencl/mesa.icd.in

**Comment by inducer** [comment]
How come it's a bad idea? (Not arguing, just genuinely curious.)

**Comment by ignatenkobrain** [comment]
usually distros has multilib support (debian puts into `/usr/lib/x86-64-gnu-linux.../`, fedora puts into `/usr/lib/` and `/usr/lib64/`).

Having architecture dependent path in architecture-independent path is always bad idea, as it causes conflicts like:
```
  file /etc/OpenCL/vendors/pocl.icd from install of pocl-0.13-4.fc25.i686 conflicts with file from package pocl-0.13-4.fc25.x86_64
```
(https://bugzilla.redhat.com/show_bug.cgi?id=1325666)

**Comment by inducer** [comment]
I can see your point for distro installs. For end-user installs to non-default locations (like `/opt/pocl`), not including the path means that users are on the hook for manually adding that path to the dynamic linker config.

The arch-dependency is just a bug that has little to do with this IMO--the `.icd` file could be called `pocl-i386.icd`, which would resolve the issue.

**Comment by kraiskil** [comment]
Appending the arch to the .icd file name would not help. The ICD loader just scans all .icd files, then talks (and asks names of the OCL implementations) to the implementation libs named there.
So both pocl-arm.icd and pocl-x86.icd would be read on both platforms, causing a similar problem.

The feature of having the full path in the .icd file is (IMHO) extremely useful in lessening confusion. Fixing it for multi-arch packaging would be a one-line post-install script, or if preferred, it could be a configure-time option (defaulting to full path!). The issue here, as I see it, I'd fix this with a note in ```README.packaging```.

**Comment by ignatenkobrain** [comment]
I would like to have configure option (or at least documentation note).

**Comment by franz** [comment]
Fixed in master
