### ISSUE TITLE
device type = 3?

### ISSUE THREAD

**Issue by cdeterman** [pocl/pocl#393]
I have recently built and installed pocl on a Ubuntu 16.04 machine.  Part of one of my opencl scripts is to check device type.  I do that with a call like the following:

```c++
clGetDeviceInfo(device_, CL_DEVICE_TYPE, sizeof(cl_device_type), static_cast<void *>(&type), NULL)

std::cout << type << std::endl;
```

Strangely, this is returning a '3' value.  I was only under the impression that 1,2,4,8, and 16 were mapped for OpenCL device types.  Any idea why I am seeing a 3 here?

**Comment by jrprice** [comment]
An OpenCL device type is a bitfield, so it can be the combination of one or more types. In this case, 3 is the combination of `CL_DEVICE_TYPE_CPU` (2) and `CL_DEVICE_TYPE_DEFAULT` (1).

The implication of this is that you should always use `&` instead of `==` when checking if a device has a certain type, e.g.:

    if (type & CL_DEVICE_TYPE_CPU)
    {
      // Do stuff for CPU devices
    }

**Comment by cdeterman** [comment]
That does the trick, thanks for clarifying.
