### ISSUE TITLE
pocl version bump needed to support latest llvm 3.9 release

### ISSUE THREAD

**Issue by victoredwardocallaghan** [pocl/pocl#401]
Hi,

A version bump is required that explicitly supports the latest llvm 3.9 release, as the current pocl 0.13 release has some breakage around 3.9.

Kindest Regards,
Edward.

**Comment by pjaaskel** [comment]
Master supports 3.9 which we release as 0.14 as soon as the remaining regressions are fixed.

**Comment by victoredwardocallaghan** [comment]
@pjaaskel thx kindly

**Comment by victoredwardocallaghan** [comment]
@pjaaskel 

Hi, sorry I didn't previously actually take enough time in explaining the reasoning behind my bug report.

The issue is at the moment Fedora is being blocked from updating mesa because mesa depends on llvm and that in turn is a req for pocl. All the other packages on the dep chain supprt the newer llvm ABI and so pocl is essentially blocking a whole bunch of packages on various critical paths from getting updated. My interest was to make note of this.

Any idea when a new pocl will perhaps be tagged?
Kindly,
Edward.

**Comment by pjaaskel** [comment]
It will be tagged when the remaining regressions have been fixed. Unfortunately I cannot give you an exact date. It's not stalled because we don't consider pocl releases important, it's just that in our group we have even more higher priority tasks at hand currently, and there seems to be not enough outside contributors to the project to make the release happen sooner. But we'll do our best...

Why cannot you package also LLVM 3.8 so you can ship pocl 0.13, or just package a pocl snapshot from git? Git HEAD is considered stable apart from the remaining regressions listed in the 0.14 milestone.
