### ISSUE TITLE
Tests fail on MacOS 10.12.2

### ISSUE THREAD

**Issue by szymoniks** [pocl/pocl#412]
Hi,

I compiled release version of LLVM 3.9 with Clang and libcxx (DBUILD_SHARED_LIBS=ON and -DLLVM_ENABLE_RTTI=ON). With it, I successfully tried to compile the latest master of POCL with no additional options for cmake (I tried version 0.13 with LLVM 3.9 and some other combinations too). However, while running tests (make check), quite a few of them fail (many from opencl-book-samples are not compiled at all) - I am not sure if that is expected?

I attach the log ([test.txt](https://github.com/pocl/pocl/files/687788/test.txt)) and would appreciate help. Thank you!

**Comment by pjaaskel** [comment]
Not sure of this as I don't use Macs. @jrprice or @eschnett might know better.

**Comment by jrprice** [comment]
I've always had a handful of test failures on macOS, but I've never got round to trying to squash them. Your failures are a slightly different set than mine, but I assume that is just because we have different CPU architectures.

The failures from `openCL_book_samples`/`piglit`/`vexcl` are annoying though - @pjaaskel shouldn't these tests just be skipped if the relevant external projects aren't available?

**Comment by pjaaskel** [comment]
Yes they should. Please try with master.

**Comment by jrprice** [comment]
OK, I forgot that you need to run `make prepare_examples`. Is it worth having `make test` depend on `make prepare_examples` to avoid these sorts of false positives?

In any case, the piglet example fails to build for me on macOS (looks like Linux specific `INSTALL_COMMAND` set to `/bin/true`, I'll try and sort this out). The `opencl_book_samples` also fails to build on both Linux and macOS, seems it can't find the SVN url - maybe that's changed and needs updating?

**Comment by pjaaskel** [comment]
Yes it would be a good idea.

**Comment by pjaaskel** [comment]
This needs help from someone who cares about pocl on MacOS.

**Comment by franz** [comment]
WRT: Is it worth having make test depend on make prepare_examples to avoid these sorts of false positives

unfortunately that'd make `make test` (and `ctest`) almost unusable, because `make prepare_examples` takes a long time even if it has already ran & built everything (because some testsuites' buildsystems fetch stuff from github on each run, and some have _slightly less intelligent_ buildsystems (aka handwritten Makefiles) which just rebuild everything everytime they're run). I tried to find a way to not run tests in ctest based on runtime conditions, but haven't found a way to do it.

WRT opencl_book_samples, i've already updated cmake to use a github repo instead of SVN.

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
