### ISSUE TITLE
LLVM 4.0: samplers broken

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#438]
This causes several tests to fail, at least these are affected:

```
 20 - kernel/test_sampler_address_clamp (Failed)
 120 - AMD_30_BufferImageInterop (Failed)
 122 - AMD_30_CalcPie (Failed)
 136 - AMD_30_ImageOverlap (Failed)
 139 - AMD_30_MatrixMulImage (Failed)
 153 - AMD_30_SimpleImage (Failed)
```

**Comment by pjaaskel** [comment]
https://reviews.llvm.org/D21567 is the reason. A slightly brutal modification considering the default case of a sampler being an i32 constant, if you ask me, but too late to complain. I think this is best handled with a custom pass that converts the initializer calls to an alloca + simple constant initializations by default.

**Comment by jrprice** [comment]
I think there's still a problem when a sampler is passed to a kernel as an argument. There wasn't any test coverage for this, so I've pushed a new runtime test:
https://github.com/jrprice/pocl/commit/9708f05ff8ff519bdd3be2dab22eb477230add59

This test passes with LLVM 3.9, but crashes with LLVM 4.0.

With 4.0, a sampler is now a pointer to the constant address space, which means that the type of these arguments has changed from `i32` to  `%opencl.sampler_t addrspace(2)*`. I guess this could just be fixed with a pass that just changes the type back to i32?
