### ISSUE TITLE
Missing retain/release for event dependencies

### ISSUE THREAD

**Issue by jrprice** [pocl/pocl#478]
When a command is enqueued with a dependency on an event, the ref count of that event should be incremented, and decremented again once the depending command has completed (or at least finished checking its dependencies). If we don't do this, that event might be destroyed before the command scheduler gets a chance to look at the dependencies (which is happening with an asynchronous implementation of command scheduling I'm working on for the CUDA backend).

The fix I want to apply here is to simply increment the event ref count in `pocl_create_event_sync`, and then call `clReleaseEvent` in `pocl_broadcast` ([see this patch](https://gist.github.com/jrprice/4dca8971102bb0ba2d3d342db96f7f2e)).

This works when I do the equivalent in the CUDA backend (which doesn't use `pocl_broadcast` in my new version), but for the pthread backend this hangs since that `clReleaseEvent` tries to lock an event that is already locked by the same thread (I think).

Using `PTHREAD_MUTEX_RECURSIVE` to allow a thread to re-lock a mutex that it has already locked would potentially solve this, but might be overkill.

Is there a better solution to this?

**Comment by franz** [comment]
The better solution is to scrap recursive processing in pthread / basic drivers, and convert all of it to queues. I doubt recursive mutex will make it more reliable.

**Comment by jrprice** [comment]
It looks like this might not actually be an issue for basic/pthread anyway, due to how they handle dependencies. An event removes itself from the wait lists of any dependent commands upon completion (before being destroyed), so the commands themselves don't actually check their dependencies explicitly.

If this is the case, I can just deal with the issue entirely inside the CUDA backend without breaking anything for any other drivers.

**Comment by pjaaskel** [comment]
@vkorhonen comments?

**Comment by pjaaskel** [comment]
@franz please explain your idea a bit better: "convert all of it to queues"? Remember that the task scheduling framework has to support cross-device distributed (hostless) synchronization with devices participating in the execution that might be more or less black boxes to the command scheduler (which need the host to synchronize their parts).

**Comment by Oblomov** [comment]
FWIW, I've had issues similar to those @jrprice mentioned even in other platforms (at least Intel's CPU proprietary one). I've gone through the OpenCL documentation a couple of times, and I see no explicit mentioning of retain/release being needed for the events in a waitlist. I must say I did find it a bit odd because the standard is typically very specific about which commands do an automatic retain/release.

**Comment by vkorhonen** [comment]
Maybe my initial idea was that event does not access its waited events so that the events could be recycled as soon as possible when they are complete. All you need to know is if there are events in the list or not. But I think that may be rather silly "optimization". Also there has not been any reason to access waited events before. I have no objections if this feature is needed.

@jrprice If you release waited event just before broadcasting the notification, then you would be recreating the problem you just had? I have no idea when do you need to access waited events.

If you need to access the wait list events, I would suggest: 

- Retaining `notifier_event` in `pocl_create_event_sync` as proposed.
- In `pocl_broadcast` the broadcasting event would not remove it self from wait lists.
- `pocl_command_is_ready` would actually go through the wait list and check event status fields.
- New utility function `pocl_event_cleanup (cl_event event)` to be called in  `POCL_UPDATE_EVENT_COMPLETE.` The function calls `clReleaseEvent()` for each wait list event.

This ensures that the driver implementation may access the wait list events until the waiting event is completed an not used anymore. Also this would fix the pocl synchronization behavior in which all the drivers could/should rely on. 

Might be good to discuss this whole events/synchronization scheme and write some documentation about the rules and fix what is handled by the runtime and what obligations/rules/working order devices have. Current situation is a bit obscure.

PS. Now that I look at the current wait list implementation, it is horrible. It would be a performance disaster to check if `pocl_command_is_ready` when the list is rather long. I have a better wait list implementation in a private repo and I should publish it in any case.

**Comment by jrprice** [comment]
> If you release waited event just before broadcasting the notification, then you would be recreating the problem you just had? I have no idea when do you need to access waited events.

In the CUDA driver the broadcast is a no-op. The events are released by the command that is waiting on them, once it is satisfied that its dependencies are all complete.

This was actually pretty straightforward to handle entirely in the CUDA backend. Inside the `submit` handler, we [perform a `clRetainEvent`](https://github.com/jrprice/pocl/blob/f9d2a7c52a3ed859bc44dc4730c3ff648ed49ab9/lib/CL/devices/cuda/pocl-cuda.c#L899) for all events in the wait list. Then, when we come to actually execute the command inside the `wait_event` handler, we [perform a `clReleaseEvent`](https://github.com/jrprice/pocl/blob/f9d2a7c52a3ed859bc44dc4730c3ff648ed49ab9/lib/CL/devices/cuda/pocl-cuda.c#L1071) for all events in the wait list, just after checking that they're all complete.

This works for CUDA, and doesn't change anything for basic/pthread, which I think were already fine because of how they handle dependencies as you describe above. I'm happy with how this is for now, but I'm definitely in favour of cleaning some of this up (and documenting it!) in the generic event handling code as well if somebody wants to do that.

**Comment by vkorhonen** [comment]
It seems that commands do not actually care about wait list at all, all commands are launched in submit? This cuda driver seems to be unable to cooperate with other device drivers?

**Comment by pjaaskel** [comment]
@jrprice @vkorhonen refers to the multi-device execution of commands (multiple CQs synchronized with events). It should be easy to test it by pairing basic/pthread with cuda and execute such test app.

**Comment by jrprice** [comment]
Right - this new async model doesn't yet have proper dependency tracking so won't work properly if used in the same context as another device driver. I'm in the process of adding CUDA event support which will fix this.

**Comment by vkorhonen** [comment]
I am not familiar with cuda. Is there a way to use cuda events to synchronize a scenario where cuda cmd is waiting for an event from for example cpu device? Or would you have to wait for cpu cmd to finish first and then launch the cuda event?

**Comment by jrprice** [comment]
I've never used it, but I believe we can do this with [cuStreamWaitValue32](http://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EVENT.html#group__CUDA__EVENT_1g629856339de7bc6606047385addbb398), which would allow us to describe an event dependency on some flag that we could control. As well as using this for synchronising with other devices, we'll also need to use this for waiting on user events.

**Comment by vkorhonen** [comment]
That is quite nice feature.

So do you need the original retain/release after all. I might commit the improved wait list implementation and add retain/release if needed.

**Comment by jrprice** [comment]
I don't need it for CUDA anymore, since I can handle it all in the driver. Feel free to close this issue unless it potentially affects other drivers (HSA?).

**Comment by Oblomov** [comment]
OK, I've gone over the spec once again, and concerning `clReleaseEvent` the text says:

> The event object is deleted once the reference count becomes zero, the specific command
identified by this event has completed (or terminated) and there are no commands in the
command-queues of a context that require a wait for this event to complete.

So, while nowhere the text says that there should be a retain/release on events in a wait list, the _effect_ of putting an event in a wait list for a command is essentially the same as a retain being there, since the event should not be destroyed anyway.

I'm not sure there's a better approach to this, unless we plan on keeping track of all the active wait lists containing each event.

**Comment by vkorhonen** [comment]
I would say it is implementation specific, because there is no need to wait `broadcast`'d event anymore in case of basic/pthread/hsa driver since the completion is explicitly stated via `notify`. 

In the cuda driver this recursive approach could be replaced with queue (with utlist.h lists) by keeping commands in a list and taking care of things from oldest to newest, or something. Then there should be no need to access wait lists. But if this is just initial step towards final cuda driver, then there is no point in getting stuck to this detail.

**Comment by jrprice** [comment]
> In the cuda driver this recursive approach could be replaced with queue (with utlist.h lists) by keeping commands in a list and taking care of things from oldest to newest, or something.

I think this is a good approach that I might switch to. The recursive version I've got in #479 works in almost all cases, but I've come across hangs in some conformance tests that assume commands are executed asynchronously after a `clFlush`. I think I'll need to add another per-command-queue background thread that cleans up commands in the order they were submitted, rather than relying on the user to call `clFinish/clWaitForEvents` and processing them recursively.

Ideally this would mean I wouldn't need to access the wait lists directly, but one issue that remains is that there is currently no way to check if any event dependencies failed (e.g. a user event was marked with a negative value in `clSetUserEventStatus`) without iterating through the wait list. This needs to be addressed to pass the `events` conformance category, and is one of the reasons why I currently access the wait list directly. I'm not sure what the best way to deal with this is that suits all the different backends.

**Comment by pjaaskel** [comment]
> I've come across hangs in some conformance tests that assume commands are executed asynchronously after a clFlush

Do you mean that they assume commands will be executed in some deterministic time, even without waiting for their events? Isn't this against the specs?

**Comment by jrprice** [comment]
> Do you mean that they assume commands will be executed in some deterministic time, even without waiting for their events? Isn't this against the specs?

Yes, the test enqueues some commands, sets up some event callbacks and calls `clFlush`, and then waits on a user event that is triggered by one of those callbacks. This assumes that those commands will definitely execute and trigger those callbacks without being explicitly waited on.

I thought this was against the specs to, but I currently can't find any wording that makes this clear.

**Comment by pjaaskel** [comment]
OK, but it waits on an event. We discussed the progress conditions a lot with Ville when designing the async execution framework to be as flexbile as possible (even to support single threaded machines), but this was years ago. Then we concluded that single threaded implementation do not need to execute anything in the background, but can just execute the commands in clWaitEvent() or clFinish(). Maybe they have added some wording that forces parallel threads?

**Comment by jrprice** [comment]
I don't think they've changed any wording about this.

For context, here's the flush in the test I'm looking at:
https://github.com/KhronosGroup/OpenCL-CTS/blob/cl12_trunk/test_conformance/conversions/test_conversions.c#L1304

and here's the wait, around 20 lines later:
https://github.com/KhronosGroup/OpenCL-CTS/blob/cl12_trunk/test_conformance/conversions/test_conversions.c#L1322

The wait is on a user event, so there is no queue associated with it - and user events have no dependencies either. There are no wait commands on any event that goes in the queue, just the flush.

**Comment by pjaaskel** [comment]
I see, user event updates via event callback(chains). Tricky, but I suppose by default it can just process all the pending commands when waiting on user events? Then single thread execution should still work.

**Comment by jrprice** [comment]
But user events are not associated with any queue or device, just a context. We'd have to go through every queue in the context and wait for them all? I don't think this would work either...

**Comment by pjaaskel** [comment]
Right. At least every _flushed_ queue in the context. Yes, there should be a more efficient option.

**Comment by jrprice** [comment]
For a simple single-threaded device the simple approach would just be to make a flush actually execute the commands, which I think is what the basic device does (and also what Oclgrind does, FWIW).

**Comment by pjaaskel** [comment]
Yes, this is what the default clFlush() used to always do before the async framework was merged in. However, I'm not sure if even that's enough in the most complex cross-queue event synchronization scenarios where commands in other command queues are blocked by each other's events and there are callback-triggered user events involved. Cannot think of a failing case quickly, but cannot prove there is none either.

**Comment by Oblomov** [comment]
A `clFlush` should not return until all commands in the queue are in the `SUBMIT` state at least, and that should be all. If this leads to some kind of deadlock, it's probably because the user set up some unresolvable cross-dependency, and honestly I don't think it should be up to the platform to guarantee that such situations be lock-free.

IME, every other platform is also very finnicky about user events in the wait list for device events. If the code that sets the user event to COMPLETE is in the main thread, and a flush hits an event that waits for this event, you _will_ get a deadlock, and there's nothing the platform can do about it.

**Comment by pjaaskel** [comment]
I believe this can be closed.
