### ISSUE TITLE
Improve code cache retrieval speed

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#480]
I'm opening this bug to get a discussion going on what can be done to make pocl faster at pulling already-built binaries out of the cache. For a lot of our development work, this is now the dominant cost. that slows down iteration time. [Here's](https://gitlab.tiker.net/inducer/sumpy/issues/18#note_14303) an example. Pocl seems roughly equally slow at loading already-built binaries keyed on OpenCL binaries and OpenCL sources. Somewhere (I can't find where right now), @pjaaskel suggested that source-based caches should be the way to go, and so I've moved in that direction. A (cluttery, sorry) `perf` profile of a program run (using the by-source cache) dominated by this looks like this:

```
  27,24%  python   libpocl.so.1.7.0            [.] clang::SourceManager::getFileIDLocal
   4,14%  python   libpocl.so.1.7.0            [.] clang::TokenLexer::Lex
   3,39%  python   libpocl.so.1.7.0            [.] SHA1_Transform
   2,66%  python   libpocl.so.1.7.0            [.] clang::TokenLexer::ExpandFunctionArguments
   2,53%  python   libpocl.so.1.7.0            [.] clang::SourceManager::getSpellingLocSlowCase
   1,81%  python   libpocl.so.1.7.0            [.] clang::TokenLexer::updateLocForMacroArgTokens
   1,69%  python   libpocl.so.1.7.0            [.] clang::TokenLexer::PasteTokens
   1,41%  python   libpocl.so.1.7.0            [.] clang::DoPrintPreprocessedInput
   1,09%  python   libpocl.so.1.7.0            [.] clang::Preprocessor::Lex
   1,00%  python   libpocl.so.1.7.0            [.] clang::SourceManager::getCharacterData
   0,91%  python   libpocl.so.1.7.0            [.] clang::SourceManager::getFileIDSlow
   0,88%  python   libpocl.so.1.7.0            [.] clang::SourceManager::getDecomposedSpellingLocSlowCase
```

For all its failings, the old AMD CPU ICD was *much* quicker at this--showing that some gains should be possible.

cc @mattwala

**Comment by inducer** [comment]
Observed on vanilla 0.14 with SPIR-CC-patched LLVM 4.0 if it matters.

**Comment by pjaaskel** [comment]
The major performance problem source-based caching is the need to preprocess the sources to produce the cache key due to command line macro defines and #includes possibly changing the source. The Clang calls are likely due to this. https://github.com/pocl/pocl/blob/master/lib/CL/pocl_llvm_api.cc#L476

Did you build Clang/LLVM with -O3? This makes a huge difference in compilation speed in general.

The preprocessing step is omitted in binary-based caching. So, in that sense you are right that binary-based (client assisted) caching is easier to make fast as the client knows exactly when the binary needs to be updated. I was just skeptical that the preprocessing time can be significant when compared to usual overall execution times (or full compilation times) of kernels. But of course if one is running a big unit test suite with small kernels, the overheads will be visible.

We might be able to make a quick shortcut to omit the preprocessing step to generate the cache key by string searching for #includes and checking the options for macro definitions. There used to be a such check when the preprocessing was not implemented. Anyways, that of course doesn't help in case one has #includes and/or macro defs.

**Comment by inducer** [comment]
> The preprocessing step is omitted in binary-based caching.

Curiously, binary- and source- based cache retrieval take about the same time for me. Binary-based used to be a win in 0.13, but it no longer is. That may hint at there being another bottleneck outside of preprocessing.

**Comment by pjaaskel** [comment]
Yes that is indeed interesting. Perhaps it (accidentally) does more compilation than preprocessing. Could you run a more informative profiler like cachegrind to get a hierarchical profile?

**Comment by inducer** [comment]
@mattwala took another look, and by (both of) our latest measurements, binary caching in 0.14 with LLVM 0.14 is actually very fast and effective. Sorry for the noise--I'm not sure what was going on back when and what exactly I measured. Closing for now.
