### ISSUE TITLE
Error compiling vecmathlib with -std=c++11

### ISSUE THREAD

**Issue by arghdos** [pocl/pocl#546]
Hi,
I'm trying to build POCL on my computing cluster, and running into problems when it begins to compile the `vecmathlib` kernels

For reference, I've attached my cmake call and output thereof [here](https://gist.github.com/arghdos/ee5d2c48e0d87a246d5d62c17bed0ba9)

The actual compilation error looks like this:
```
Building C++ to LLVM bitcode /home/njc07003/src/pocl/build/lib/kernel/host/broadwell/acos.cc.bc
cd /home/njc07003/src/pocl/build/lib/kernel/host && /apps2/clang/5.0.0/bin/clang++ --target=x86_64-unknown-linux-gnu -D_CL_DISABLE_HALF -march=broadwell -emit-llvm -ffp-contract=off -DVML_NO_IOSTREAM -std=c++03 -I/home/njc07003/mod/ocl-icd/include -D__OPENCL_VERSION__=120 -Dcl_khr_int64 -Dcl_khr_byte_addressable_store -Dcl_khr_global_int32_base_atomics -Dcl_khr_global_int32_extended_atomics -Dcl_khr_local_int32_base_atomics -Dcl_khr_local_int32_extended_atomics -Dcl_khr_3d_image_writes -Dcl_khr_fp64 -Dcl_khr_int64_base_atomics -Dcl_khr_int64_extended_atomics -Xclang -cl-ext=+cl_khr_byte_addressable_store,+cl_khr_global_int32_base_atomics,+cl_khr_global_int32_extended_atomics,+cl_khr_local_int32_base_atomics,+cl_khr_local_int32_extended_atomics,+cl_khr_3d_image_writes,+cl_khr_fp64,+cl_khr_int64_base_atomics,+cl_khr_int64_extended_atomics, -std=c++11 -o /home/njc07003/src/pocl/build/lib/kernel/host/broadwell/acos.cc.bc -c /home/njc07003/src/pocl/lib/kernel/vecmathlib-pocl/acos.cc
In file included from /home/njc07003/src/pocl/lib/kernel/vecmathlib-pocl/acos.cc:3:
In file included from /home/njc07003/src/pocl/lib/kernel/vecmathlib-pocl/pocl-compat.h:8:
In file included from /home/njc07003/src/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/vecmathlib.h:109:
/home/njc07003/src/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/vec_sse_float1.h:397:39: error: conversion from 'typename
      __gnu_cxx::__enable_if<__is_arithmetic<float>::__value, int>::__type' (aka 'int') to 'vecmathlib::realvec<float, 1>::boolvec_t' (aka 'boolvec<float, size>') is
      ambiguous
  boolvec_t isfinite() const { return vml_std::isfinite(v); }
                                      ^~~~~~~~~~~~~~~~~~~~
/home/njc07003/src/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/vec_sse_float1.h:67:3: note: candidate constructor
  boolvec(bvector_t x) : v(x) {}
  ^
/home/njc07003/src/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/vec_sse_float1.h:68:3: note: candidate constructor
  boolvec(bool a) : v(a) {}
  ^
(and 9 more identical errors)
```

(also attached)  -- the only reference I've been able to find on this is from a [very old](https://sourceforge.net/p/pocl/mailman/message/31155176/) mailing list message (for v0.8) that suggests that the `-std=c++11` flag is to blame.

So a few questions:
1.  Is this still true?
2.  If so, I believe the `-std=c++11` is coming from my LLVM_CXXFLAGS:

`-- LLVM_CXXFLAGS: -I/gpfs/gpfs1/apps2/llvm/5.0.0/include  -fPIC -fvisibility-inlines-hidden  -std=c++11           -g  -fno-exceptions -fno-rtti -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti`, or at least that is the only place that flag shows up in the configure output.

What would be the best way to remove it?  I've tried to pass in an earlier standard via:

`-DEXTRA_KERNEL_CXX_FLAGS="-std=c++03"`

but it is simply overridden as the `-std=c++11` flag appears later in the compilation

**Comment by franz** [comment]
Hello,

The `-std=c++11` flag is not coming from LLVM_CXXFLAGS, those flags are only used to compile the LLVM-related part of pocl, not the kernel library. The kernel library `-std=c++11` flag is coming from https://github.com/pocl/pocl/blame/master/cmake/bitcode_rules.cmake#L65  where it's hardcoded for vecmathlib's C++ files.

Looking at git blame, it has been there for a year - and nobody has reported any problems with this (i've been compiling it almost daily), so the sources or the C++11 flag is not the problem.

I think the problem is that you're using both GCC and Clang installed in non-default locations and passing args like -DCMAKE_CXX_LINK_FLAGS to CMake to get it working. This might get you a working GCC invocation where pocl lets CMake invoke the compiler, but the kernel library compilation is using handwritten rules with custom CMake commands/targets. Perhaps you could try to invoke CMake with `-DEXTRA_KERNEL_CXX_FLAGS=-I/home/njc07003/mod/ocl-icd/include -Wl,-rpath,/apps2/gcc/5.4.0-alt/lib64 -L/apps2/gcc/5.4.0-alt/lib64 -L/home/njc07003/mod/ocl-icd/lib/`or something like that, or fiddle with bitcode_rules.cmake directly.

You could try going into `<BUILDDIR>/lib/llvmopencl` and run `make VERBOSE=1` and see how CMake invokes the c++11 compiler, and if it works. BTW i believe LLVM now requires a C++11 compiler to compile, which also means pocl requires it, so `-std=c++03` will not help you.

**Comment by arghdos** [comment]
@franz it turned out I needed to use the `--gcc-toolchain` [option](https://stackoverflow.com/questions/41962611/how-to-select-a-particular-gcc-toolchain-in-clang) to clang via the `-DEXTRA_KERNEL_CXX_FLAGS` to direct to both the correct `libstdc++` and the correct include directories for standard headers.

Thanks your help, the comment regarding putting the runpath into the `EXTRA_KERNEL_CXX_FLAGS` pointed me in the right direction.
