### ISSUE TITLE
barrier in auxiliary function confuses pocl?

### ISSUE THREAD

**Issue by SyamGadde** [pocl/pocl#548]
I'm having trouble drilling down to a general description of this problem, but the following simplified code causes some unexpected behavior.  There are two `if` clauses that test whether the local id (as fetched using get_local_id(0)) is 0.  In between the two clauses is a call to an auxiliary function that calls a barrier.

The problem happens with workgroups of any size, but with a workgroup size of two, I would expect each printf to print twice, once with id=0 and once with id=1.  However the CCC printf between the two `if` clauses prints with id=0 twice.  It's almost as if the compiler is seeing both `if (id == 0)` clauses on either side and just setting id to zero for the code in between.

If you comment out any of the lines marked with an XXXX, it works as expected.  i.e. if:

- one of the clauses doesn't test whether id is 0, or
- if you get rid of the barrier, or
- make one of the clauses empty, or 
- figure out how to let the compiler optimize out one or both of the if clauses (see the `x = 1` in the first clause)

then it works as expected.

Code below.   I tested with commit e3fff28711a5ad3aae5c2f10d554012c6be0a961 (cloned from github early Oct 24), and LLVM 5.0.0.  If you need any more info, please let me know.  Thanks for any assistance!

```
inline
void
auxfunc()
{
    printf("auxfunc\n");
    barrier(CLK_LOCAL_MEM_FENCE); // XXXX
}


__kernel
void
mykernel() {
    int id = get_local_id(0);
    int localsize = get_local_size(0);
    __local int x;

    // For a workgroup size of 2, we expect CCC to be printed twice,
    // with id=0 and id=1 but the printfs have id=0 for both work-items.
    // Comment out any one or more lines marked XXXX and it works as expected.

#define TESTID1 // XXXX
#define TESTID2 // XXXX

#ifdef TESTID1
    bool test1 = (id == 0);
#else
    bool test1 = true;
#endif
#ifdef TESTID2
    bool test2 = (id == 0);
#else
    bool test2 = true;
#endif

    printf("id=%d: AAA.\n", id);
    if (test1) {
	x += 1; // XXXX
	//x = 1; // uncomment this line and it also fixes it
    }
    printf("id=%d: CCC.\n", id);
    auxfunc();
    if (test2) {
	x = 1; // XXXX
    }
    printf("id=%d: EEE.\n", id);
}
```

**Comment by pjaaskel** [comment]
Does it work if the auxfunc() is manually inlined to the call position, that is, the barrier is not inside a function call? Does it work with pocl 0.14? I think this might be due to the new inlining logic. In the past we relied on fully inlining functions to the kernel, also because the possible barrier calls inside the subfunctions can be then analyzed by just analyzing the kernel. If it is not inlined for a reason or another, then the WGF analysis might fail.

**Comment by SyamGadde** [comment]
Yes, it does work if the barrier is moved from the auxiliary function to the main function.  I will try pocl-0.14 (looks like I'll need to grab llvm-4.0.1 for that).

**Comment by pjaaskel** [comment]
I think this might be a Clang/LLVM bug. Some function attributes such as 'noduplicate' should be propagated to the caller function, otherwise the caller can be duplicated in its caller and thus the called function (in this case the barrier, which is marked with 'noduplicate') will get illegaly duplicated. Somehwat confusing explanation? :P    You can see the effect by manually adding '__attribute__((noduplicate))' to your auxfunc(). 

I think Clang should do that automatically (internally) when it sees the function calls a noduplicate function. Not sure yet what's the best way to workaround this in pocl code base, in case it indeed turns out to be a Clang bug. Perhaps we need to avoid any optimizations in Clang and then propagate the attributes in our own custom pass.

**Comment by pjaaskel** [comment]
This is fixed for CUDA in Clang 5.0, and seems to be fixed also for OpenCL in LLVM trunk: https://github.com/llvm-mirror/clang/blob/master/lib/CodeGen/CGCall.cpp#L1753  thus, after pocl is ported for the new Clang, this bug should go away.

**Comment by SyamGadde** [comment]
Thanks for investigating this and for the pointer!  For the time being I'll use the \_\_attribute((noduplicate))\_\_ workaround.

**Comment by pjaaskel** [comment]
This should get fixed for the next release after the currently prepared one with support for upcoming Clang 6.0.
