### ISSUE TITLE
macOS build broken for absence of pthread_spinlock_t

### ISSUE THREAD

**Issue by blu** [pocl/pocl#569]
As of cd4936b57c30292f2f950013317e66958b94ff8e macOS build is broken:

```
In file included from /Users/user/proj/pocl/lib/CL/devices/pthread/pthread.c:30:
/Users/user/proj/pocl/lib/CL/devices/pthread/pocl-pthread_utils.h:41:3: error: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
  pthread_spinlock_t lock __attribute__ ((aligned (HOST_CPU_CACHELINE_SIZE)));
  ^~~~~~~~~~~~~~~~~~
  pthread_rwlock_t
```

**Comment by franz** [comment]
That's easy enough to fix (although i find it weird, quick search says spinlocks are part of POSIX, but perhaps it's an optional part)... but the real question is, are you willing to put in more effort. There are likely dozen more broken things on macOS, because about once in a year somebody builds pocl on mac, and then it gets abandoned.

**Comment by blu** [comment]
Unfortunately pthreads on macOS are incomplete (e.g. pthread_barrier is another victim there). Ok, I'll attend to the issue when I get more spare time, but that will surely involve adding an arbitrary-ugly pthread_spinlock implementation to pocl/macOS.

**Comment by franz** [comment]
> arbitrary-ugly pthread_spinlock implementation to pocl/macOS.

Actually, i think my adding of spinlock was not having as much effect as i thought (mostly because i was measuring a somewhat special case), so just ifdef to classic pthread mutex should work reasonably well. Or perhaps Mac has it's own locking libraries, dunno.

**Comment by franz** [comment]
Should be fixed in master
