### ISSUE TITLE
cannot use own ICD library - CHECK_FUNCTION_EXISTS fails

### ISSUE THREAD

**Issue by kostik-b** [pocl/pocl#578]
When supplying own `libOpenCL.so` file with `-DENABLE_ICD=1` flag the cmake fails to execute `CHECK_FUNCTION_EXISTS` macro (around line 619):

```c
 set(HAVE_OCL_ICD 0 CACHE INTERNAL "ICL library is ocl-icd")
    # fallback to other ICD loaders
    message(STATUS "ocl-icd not found -> trying fallback ICD implementations")
    pkg_check_modules(OPENCL OpenCL>=1.2)
    if(NOT OPENCL_FOUND)
      find_library(OPENCL_LIBRARIES OpenCL)
      # version check the found library
      if(OPENCL_LIBRARIES)
        set(CMAKE_REQUIRED_LIBRARIES "${OPENCL_LIBRARIES}")
        include(CheckFunctionExists)
HERE ---> CHECK_FUNCTION_EXISTS("clEnqueueFillImage" OPENCL_FOUND)
      endif()
    endif()
```

The reason for this is that `OPENCL_FOUND` is already set by the previous call to `pkg_check_modules`. When looking at the cmake source code in Modules/CheckFunctionExists.cmake it becomes apparent that `CHECK_FUNCTION_EXISTS` will only execute if the variable `OPENCL_FOUND` is not set, which is not the case in this code. A single line `unset (OPENCL_FOUND CACHE)` just above the macro call solves the problem.

**Comment by kostik-b** [comment]
I should have mentioned that the problem happens in the main `CMakeLists.txt`.

Please advise what should I do next? If you are happy with the fix, should I submit the pull request? I have never done this on GitHub, so I would like to go through the steps involved, if possible.

**Comment by franz** [comment]
So what you're saying is, an unsuccessful call of ``pkg_check_modules()`` sets OPENCL_FOUND to some false value, and then ``CHECK_FUNCTION_EXISTS`` checks for undefined rather than  false variable (``if(NOT DEFINED "${VARIABLE}"  ...``) ? yes i think the unset should work.

You could submit a PR, but this is quite a tiny fix, i can just add it on top of my current PR.

**Comment by kostik-b** [comment]
That's exactly right. I have just checked and I cannot see where in `pkg_check_modules` the `OPENCL_FOUND` is getting defined, but it is does appear to be somehow defined.

Would you mind if I go down the PR route, if this is not too much hassle for you? I am new to GitHub, so I would like to try it out. Also I get all the blame if I accidentally ruin things :) And if not, this will be a little bonus for my public portfolio.

**Comment by kostik-b** [comment]
Just had a second look and found it. In Modules/FindPkgConfig.cmake the variable `OPENCL_FOUND` is unset inside a macro `_pkgconfig_unset`. That macro "unsets" variables by setting them to empty string.

**Comment by kostik-b** [comment]
Btw, can I use this opportunity to ask a question here? When building POCL (v 0.14) I have noticed that some LLVM paths are getting hardcoded/embedded into POCL source code, e.g. SRCDIR and PKGDATADIR in `pocl_llvm_api.cc`, as well as `CLANGXX` in `devices/common.c`. Is that an intended design trait or a leftover from the prototype stage?

**Comment by franz** [comment]
OK, the PR workflow is quite easy: you can create a PR on any branch you have pushed to github. So just fork pocl on github, clone to local computer, fix, push branch with fix (can also be master) to github, then submit PR.

> SRCDIR and PKGDATADIR in pocl_llvm_api.cc, 

This is intentional - part of pocl is a compiler, and you need to access certain headers and sources to compile OpenCL programs. There is a environment variable called POCL_BUILDING which when set to 1, makes pocl search for those headers/sources in the build directory (instead of install locations) so this is useful for testing out pocl without installing.

I've recently added a cmake variable ``ENABLE_POCL_BUILDING``, if you run ``cmake -DENABLE_POCL_BUILDING=0`` then those paths won't be embedded but POCL_BUILDING will have no effect (obviously). If you're doing some sort of packaging, perhaps [this](https://github.com/pocl/pocl/blob/master/README.packaging) could be useful 

> CLANGXX in devices/common.c

I think this was because pocl used clang to link a program (produce an .so which was then dlopen-ed). Current git master uses ``ld``, so you'll likely find ``/usr/bin/ld`` hardcoded in libpocl.so

**Comment by kostik-b** [comment]
Ok thanks! I'll start the PR process now.

**Comment by franz** [comment]
@kostik-b  i think - i'm not 100% sure - if your commit message says "fix #NUM" instead of "Issue #NUM"
then merge of PR will automatically close the bug. Just FYI
