### ISSUE TITLE
no inlining of the work-group function

### ISSUE THREAD

**Issue by jianbinfang** [pocl/pocl#584]
Hey Guys, 

I noted that pocl removes the inline of the work-group function (_pocl_launcher_**) in workgroup.cc. 

I wonder why we remove the function inline, since inlining the workgroup function will give a performance improvement. 

Regards,
Jianbin

**Comment by franz** [comment]
> since inlining the workgroup function will give a performance improvement.

it also makes it impossible to call the workgroup function :) that would be the main reason it's not inlined.. 

The kernel compilation produces a .so which is then dlopen()-ed, and you need to get the address of the kernel function to launch it. Inlined functions don't have an address (in fact they're not functions at all since there's no stack entry/exit at all).

**Comment by franz** [comment]
Apologies, i think i misunderstood the question. If you're asking why ``_pocl_launcher_<kernel>_workgroup`` does not inline ``_pocl_launcher_<kernel>``, the answer is it's probably not worth it, since there's only one call and it only happens once per workgroup, not once per work-item. Have you measured any performance improvement with inlined kernel ?
