### ISSUE TITLE
Does not report linker failure

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#593]
If linking the kernel fails, no error is reported. A problem only becomes apparent when the kernel is run, when an error like the following is shown:

```
python: /feedstock_root/build_artefacts/pocl_1513909096286/work/pocl-1.0/lib/CL/devices/common.c:913: pocl_check_dlhandle_cache: Assertion `cmd->command.run.wg != ((void *)0)' failed.
```

Reproducible e.g. by specifying an invalid `LINK_COMMAND` during build.

(Observed on 1.0 using Linux.)

**Comment by franz** [comment]
> specifying an invalid LINK_COMMAND during build.

I just tried that, and it triggers something entirely else - a segfault in ``lt_dlopen()``.

The assertion you mentioned happens when  ``lt_dlopen()`` is successful but ``lt_dlsym(kernel_wg_function_name) `` fails for some reason. I have no idea yet how that could happen

**Comment by inducer** [comment]
My hope when reporting the bug was that pocl might catch the linker failure itself and never even attempt `dlopen` or `dlsym`.

**Comment by franz** [comment]
I can add an error handler to fix the asserts / segfaults, but the only possible options are 1) retry 2) abort 3) let clEnqueueNDRangeKernel fail its event with an error.

There's no way to return an error from clBuildProgram() because the last two steps of building happen in the driver, long after any clBuildProgram(). This is because of the way pocl was designed (to use the local WG sizes from clEnqueueNDRangeKernel() as an optimization hint). There are some ways to fix this, but each will likely require some redesign. Anyway i think there's a genuine bug somewhere in the ltdl code (or cache or some race somewhere) which won't be fixed by this, so i'm looking at that first..

**Comment by inducer** [comment]
If you're taking votes, mine would be

> 3) let clEnqueueNDRangeKernel fail its event with an error.

and, ideally, make some noise on stderr.

**Comment by franz** [comment]
Unfortunately, 3. is not a full solution, since that's only possible when ``clEnqueueNDRangeKernel`` is called with non-NULL ``cl_event *event`` argument. If it's NULL, pocl would have to do something else (probably fail the entire queue).

Anyway, last PR (#606) revamped the cache and the dlopen handling. There was a not-quite-obvious bug in pocl's dlcache code, which i think caused those ld_dlsym / lt_dlopen problems. Linker failure now leads to an abort, but hopefully the underlying bug was fixed...

I'll keep this bug open for a while; in case you run into the problem again, please let me know here.

**Comment by franz** [comment]
@inducer hi, are you still having this problem with 1.1 RC1/2/3 ?

**Comment by inducer** [comment]
Nope, looks fixed. Thanks!

**Comment by inducer** [comment]
(on 880469b0)
