### ISSUE TITLE
 [LLVM 7.0] SPIR support is not available for device

### ISSUE THREAD

**Issue by yu810226** [pocl/pocl#615]
Hi, 
I am working on making pocl work with latest LLVM 7.0 on github. After changing codes in 
[this commit](https://github.com/yu810226/pocl/commit/5b46e01991a9a89291b423c2d35f639c1a8ffefe), it is well compiled.
However, I ran into the problem that SPIR support is not available for device pthread-Intel(R) Core(TM) i7-6700 CPU. And looks like the problem is caused by code added in `lib/CL/pocl_build.c` from [this commit](https://github.com/pocl/pocl/commit/e4c1a2e0c64b4f89d07f0860488400f38de8feee). Condition `!strstr (device->extensions, "cl_khr_spir")` leads to pocl run time error: SPIR support is not available for device.
Is there a reason why `cl_khr_spir` is no longer default for CPU device?
Thanks!

**Comment by franz** [comment]
> Is there a reason why cl_khr_spir is no longer default for CPU device?

Yep. The original SPIR support was an ugly hack, which "worked" when you tried them on hello-world style programs. Then at some point before 1.0 we moved the "link the program to kernel library" build step into program.bc (instead of parallel.bc), which completely broke SPIR; some details are in issue #521. I created new SPIR binaries for the tests, but later i decided it's better to stop pretending pocl supports something it actually doesn't, that's why there's no `cl_khr_spir` anymore.

I've already said what are the two options to get proper SPIR support: 1) translate the SPIR(-V) to LLVM IR somewhere early in build process, or 2) build an entire SPIR kernel library. I suspect 2) is easier.

**Comment by keryell** [comment]
This is annoying because PoCL has been very useful up to now to help the development of other projects such as https://github.com/triSYCL/triSYCL and other Khronos work.
Would it be possible to have a CMake option to have the `cl_khr_spir` back even with OpenCL 1.2?
We can make a PR...
Do not be too modest about your SPIR support. Would it be just quite minimalistic, at least it does exist. :-)

**Comment by pjaaskel** [comment]
PR sounds good :)

**Comment by yu810226** [comment]
Thanks for the reply! I made a PR for this. :-)

**Comment by franz** [comment]
Unfortunately that PR doesn't resolve anything. But the good news is, we will likely need SPIR support soon for a different project, so the experimental version will be back in POCL in 1.1 (i already have the code).

**Comment by keryell** [comment]
This PR solves our issue: having some minimal SPIR support as before, if required.
Of course if your expectation was to have full SPIR support... Sorry. :-)
Otherwise, nice that you already have the code for SPIR.

**Comment by franz** [comment]
> Of course if your expectation was to have full SPIR support

No, my expectation was to have the same level of experimental support as was available before (i.e. around pocl 0.14 i think) - and this PR does not provide that. Perhaps you got the impression that it does because with this PR, ``example1-spir64`` passes. It passes because when i broke SPIR support, i manually hacked the spir bitcode of example1 to include the required kernel library functions to make the test pass, before i realized how foolish that effort is. If you recompile example1.cl (or any other cl source) to SPIR with ``clang <flags> -emit-llvm -target spir64-unknown-unknown -o example1.spir -c example1.cl`` and run it, it'll do this:

     ./examples/example1-spir64/example1-spir: symbol lookup error: .../dot_product/128-1-1/dot_product.so: undefined symbol: _Z13get_global_idj

That's because ``get_local_id`` and ``get_global_id`` are kernel library functions, and this PR doesn't solve the linking issue. Without get_global_id or indeed the entire kernel library,  i'd call the level of support it provides "purely fictional" instead of "minimal" ;) ... which is why i disabled it for 1.0 release (and NACKed the PR).

**Comment by franz** [comment]
OK, this is fixed in master - 4de707cbb364f0e87a8f06 and a few more commits
