### ISSUE TITLE
strdup(), _POSIX_C_SOURCE, and glibc version

### ISSUE THREAD

**Issue by noma** [pocl/pocl#678]
In PoCL-1.2, [`pocl-1.2/lib/CL/devices/common.c`](https://github.com/pocl/pocl/blob/23a0eed447509a9cdc706f39302037ef67b160b1/lib/CL/devices/common.c#L27)

```c
/* for posix_memalign and strdup */
#define _DEFAULT_SOURCE
#define _POSIX_C_SOURCE 200809L 
```
There was a fix of the _POSIX_C_SOURCE value here https://github.com/pocl/pocl/pull/650/commits/19c5a605f64f202d5db1247a9ddd3c7d4521b6d4, related: #654 #650  

For glibc versions < 2.12, this does not work, here is the requirement for `strdup` to be visible, according to [here](https://linux.die.net/man/3/strdup):
``` 
_SVID_SOURCE || _BSD_SOURCE || _XOPEN_SOURCE >= 500 || _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED
|| /* Since glibc 2.12: */ _POSIX_C_SOURCE >= 200809L 
```

I tried to create a fix that checks for the glibc version and defines one of the above, or just `_GNU_SOURCE`, however, the version macros come from `features.h` or `gnu/libc-version.h` which includes the former, which also evaluates the `_*_SOURCE` macros, i.e. they must be set before including `features.h`, i.e. before we have the version information.

Since a glibc version check seems not possible here in a non-hacky way, `_POSIX_C_SOURCE` should be replaced, or accompanied by one of the other macros in order to work with older glibc-versions, which sadly can still be found in production (I'm compiling on a ~1 PFLOPS Top500 system here). 

I am not uncertain which macro to pick, as I am not that familiar with the PoCL code base and possible implications on compiler compatibility and other parts of the code. I am currently working with the following patch:

```c
// if a GNU compiler is found, enable _GNU_SOURCE
#ifdef __GNUC__
#define _GNU_SOURCE
#endif
```

**Comment by franz** [comment]
> Since a glibc version check seems not possible here in a non-hacky way,

detecting glibc version would have to be added to CMake, but i don't think it makes sense to detect the version, pocl merely needs to detect which macro(s) make the function available.

> I am currently working with the following patch:

I think we could just add a ``#define _BSD_SOURCE``, since ``_DEFAULT_SOURCE`` which is already there, implies ``_BSD_SOURCE`` (on systems which are new enough to recognize  ``_DEFAULT_SOURCE``). On older systems which don't recognize ``_DEFAULT_SOURCE``, ``_BSD_SOURCE`` should be enough to get ``strdup``, which AFAICT is the only strdup variant used by Pocl. Can you try adding ``#define _BSD_SOURCE`` right before ``_DEFAULT_SOURCE`` ?

**Comment by isuruf** [comment]
Fixed in https://github.com/pocl/pocl/pull/695
