### ISSUE TITLE
Device side enqueue support

### ISSUE THREAD

**Issue by cjdelisle** [pocl/pocl#715]
Opening this issue as a place to discuss the topic of device side enqueue.

Currently, casting a block to a pointer causes a linker error because (AFAIU) the optimization passes inline and then erase all non-kernel functions. In order to support a most simplistic implementation of "device-side enqueue" with the pthread backend, we would at least need to be able to take the pointer of a block function and then convert that into a kernel.

Is there anything I'm missing here ?

**Comment by pjaaskel** [comment]
Thanks for working on this @cjdelisle. I think these type of discussions are better had in the mailing list, not in an issue tracker, though. But it's up to you.

I haven't personally given much thought to the device side enqueue yet, but quickly thinking: Overall the block functions shall be converted into kernel functions which then must be processed by the WG function passes also (but exactly _when_ is a bit unclear). Remember that we generate WG functions that execute all WIs for the "MIMD devices" such as CPUs (pthread/basic) from the single work-item kernel functions which are then loop vectorized or whatever is preferred for the device at hand.

If there's a robust way to recognize these block functions from Clang, we can just add the kernel attribute to them (it'd be better done by Clang instead really, and be something that distinguishes them from "main kernels"). Then in the enqueue_kernel() we might just refer to them by name (assuming the block function name is mangled/made impossible to not conflict with normal kernel names). Then the enqueue_kernel should get access to the driver layer's queuing APIs where it uses driver-specific means to queue the kernel to get async execution in case of multiple threads with the event updated.

Remember that the "means" must be generic enough to support heterogeneous devices as well, but we might hide the means chosen in a device-specific queue_t. Perhaps just pass a void* as queue_t and it's device-specific what that is (e.g. in HSA case it could be e.g. directly the queue location in SVM, in pthread a pointer to the device driver instance or similar).

One detail that needs to be thought through is the compilation process: Currently we assume that there is a single main kernel function per kernel command, and optimize accordingly. We specialize the WG function per local size, for example, but I'm unsure how much this benefits nowadays with improved vectorizers etc. in place (which can add specializing code with vector width checks).

In this case we have to compile (preferably beforehand to utilize the caching mechanism) all the kernels involved in the device-side queueing and the local size might not be known until it's launched from the main kernel. Thus, before launching the "main kernel", the subkernels must be processed and compiled as well such that when the main kernel finally launches the subkernel in question, or compiled on the fly before launched. Since this scheme must work also when starting from the binaries, we might need to compile all the subkernels to dynamic local size WG functions to the main kernel binary while compiling the main one, which should make the execution time simpler.

@AlexeySachkov or @asavonic any further insight/tips to this?

**Comment by cjdelisle** [comment]
> I think these type of discussions are better had in the mailing list
I will register on the list so i can stay up to date.

> If there's a robust way to recognize these block functions from Clang
I created [a toy project](https://github.com/cjdelisle/pocl-enqueue) to demonstrate what happens when you attempt to take the pointer of a block, the result of compiling it is here:

```
Undefined symbols for architecture x86_64:
  "___cl_main_block_invoke", referenced from:
      ___block_literal_global in tempfile-ee-da-cf-7b-9e.so.o
ld: symbol(s) not found for architecture x86_64
error: linker command failed with exit code 1 (use -v to see invocation)
Final linking of kernel cl_main failed.
Abort trap: 6
```

After a little bit of testing, I found that the names of the first block is `__<kernel_name>_block_invoke` and the second is `__<kernel_name>_block_invoke_2` and so on. Note that my machine is OSX so the ABI is adding another `_`. I'm not sure if detecting `block_invoke` is adequately robust for recognition but it could be a starting point.

> Then the enqueue_kernel should get access to the driver layer's queuing APIs where it uses driver-specific means to queue the kernel to get async execution in case of multiple threads with the event updated.

My preference here is to have a shim library which implements enqueue by shoving the kernel out to host-land and then using `clEnqueueNDRangeKernel` to enqueue it because:

1. Lots of devices are too old to run OpenCL2.0
2. In order to keep my binary sizes down, I prefer to ship only my opencl source or SPIR-V plus a compiled linked x86 implementation of my opencl code bundled with the pthread backend and then have my program opportunistically use the installed OpenCL library or fallback to pthread.

FYI my main motivation for interest in pocl device enqueue is an [opencl-experiment](https://github.com/cjdelisle/opencl-experiment) with using libuv to attempt at writing entire programs in opencl.

**Comment by pjaaskel** [comment]
Unfortunately the name might not be enough as it contains valid characters only which might be produced but indeed might be good for a starting point and a proof of concept.

If you want to call clEnqueueNDRangeKernel then you need the cl_kernel built from those kernels. It might work if clBuildProgram() detects the blocks as kernels and treats them as ones and then you can refer to it by that magic name from the enqueue_kernel() implementation.

Interesting experiment. Reminds me of some previous works which execute host syscalls from the device by "calling back" host via SSVM shared variables. I'm not completely sure on details of what you try to accomplish, but did you notice that enqueue_kernel() should target the same device, thus officially cannot be used to queue kernels to others?

**Comment by cjdelisle** [comment]
> It might work if clBuildProgram() detects the blocks as kernels and treats them as ones and then you can refer to it by that magic name from the enqueue_kernel() implementation

That sounds about right, we just need to transform the functions into kernels.

> I'm not completely sure on details of what you try to accomplish

What I'm imagining is being able to write general purpose code (e.g. web-app, dns, etc) which contains a certain amount of computation but also a certain amount of traditional data processing but which runs entirely on a GPU and trades execution latency for thread count.

> but did you notice that enqueue_kernel() should target the same device, thus officially cannot be used to queue kernels to others?

In my experiment, there is a message queue between "host code" and "device code" and enqueued kernels are only there for creating a callback system to be called after some asynchronous event is complete, so no need to enqueue cross-device, even with code running on different devices...

**Comment by pjaaskel** [comment]
Was there any progress with this?
