### ISSUE TITLE
"fill_buffer" is unimplemented in CUDA

### ISSUE THREAD

**Issue by kif** [pocl/pocl#725]
Hi,

I found PoCL useful to profile my opencl kernels on nvidia hardware. There is a missing feature which is probably trivial to implement as apparently it is not possible to fill an array with a given value in CUDA. Writing a kernel that does it not that difficult, but how to integrate it into PoCL?
Apparently it correspond to the clEnqueueFillBuffer from OpenCL.

Here is the exception I got:
fill_buffer is unimplemented (.../debian9/pocl-1.2/lib/CL/devices/cuda/pocl-cuda.c:1235)

**Comment by jrprice** [comment]
I think the simplest approach would be to write the kernel in CUDA, and use `nvcc` to compile it to PTX at pocl build time. We'd need to install it somewhere, probably alongside the device bitcode library, and it could then be loaded and used by the runtime relatively easily. Does this sound reasonable @pjaaskel ?

Writing it in OpenCL and adding it to the device bitcode library as LLVM IR is the other option, but I think it would add a lot of complexity since we'd have to do the LLVM->NVVM conversion pass and PTX generation at runtime (during device initialisation) before we could use it (although it could be cached like other kernels, so shouldn't affect performance).

**Comment by kif** [comment]
Maybe I don't understand where the issue is, but to me, the function enqueue_fill_buffer 
https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueFillBuffer.html
looks like executing a kernel similar to this:
```
kernel void fill_buffer(global char *buffer, 
                                    global char *pattern, 
                                    size_t pattern_size, 
                                    size_t offset, 
                                    size_t size)
{
    size_t start = offset + pattern_size*get_global_id(0);
    for (size_t idx=start; idx<start+pattern_size; idx++)
    {
        buffer[start+idx] = pattern[idx];
    }
}
```
The main drawback is that the pattern has to be transferred to global memory beforehand and cannot be sent directly to shared-memory. The alternative I see is to specialize the function depending on the pattern_size, from 1 to 128 (double16).

What do you think ?

**Comment by Oblomov** [comment]
I highly recommend having specialized functions based on `pattern_size`, there are dramatic performance differences. Basically anything that isn't 16-bytes should shuffle the pattern/work-item mapping so that each work-item writes out the equivalent of an `uint4`.

* pattern size 1 should have a `uchar` pattern and each workitem write an `(uint4)(pattern)`;
* pattern size 2 should have a `ushort` pattern and each workitem write an `(uint4)(pattern)`;
* pattern size 4 should have a `uint` pattern and each workitem write an `(uint4)(pattern)`;
* pattern size 8 should have a `uint2` pattern and each workitem write an `(uint4)(pattern)`;
* pattern size 16 should have a `uint4` pattern and each workitem write `pattern`;
* pattern size 32 should have a `uint8` pattern and workitems should write out `pattern.lo` and `pattern.hi` depending on index parity;
* pattern size 64 should have a `uint16` pattern and workitems should write out `pattern.s0123`, `pattern.s4567`, `pattern.s89ab` and `pattern.scdef`` depending on index % 4;
* pattern size 64 should have a `ulong16` pattern and workitems should write out `pattern.s01` to `pattern.sef` depending on index % 8.

**Comment by Oblomov** [comment]
Hm, after some thinking, I believe the first two are wrong. The `uchar` and `ushort` should first be duplicated across a single `uint` before being duplicated across a `uint4`. So something like this:

```
uint pat = pattern; // promote to right size
// either of these two:
pat |= (pat << 8) | (pat << 16) | (pat << 24); // duplicate uchar pattern across entire uint
pat |= (pat << 16); // duplicate ushort pattern across entire uint
// and finally the uint4 version:
const uint4 to_write = (uint4)(pat); // duplicate across a uin4
```

**Comment by jrprice** [comment]
@kif There's no issue, I was just pointing out that it'd be simpler to implement this kernel in CUDA rather OpenCL, otherwise we'd have to perform a bunch of transformations on the LLVM that Clang generates to make the compiled kernel compatible with the CUDA backend.

Having specialised routines for each pattern size sounds sensible too.

**Comment by isuruf** [comment]
I decided to just use the CUDA driver functions for `pattern_size` of `1,2,4` at https://github.com/pocl/pocl/pull/834
