### ISSUE TITLE
Ubuntu 18.04 LLVM 7 issue

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#728]
Cmake doesn't find the non-default LLVM 7 which is shipped with Ubuntu 18.04 as it doesn't look for llvm-config-7. Adding that to CMake build checks fixes the build mostly, but then it seems to fail at link time due to not having /usr/lib/x86* where libOpenCL.so is located. I guess the default llvm-config --ldflags adds that and the non-default doesn't.

**Comment by franz** [comment]
> it seems to fail at link time due to not having /usr/lib/x86* where libOpenCL.so is located

`/usr/lib/x86_64-linux-gnu` is the default library path on x86-64 ubuntu, and AFAIK the linker always looks there unless explicitly told not to. I have never seen a pocl build on Ubuntu not find libOpenCL.so in the standard path; so maybe it's some other library you're actually missing, or your ubuntu system is somehow misconfigured. I have multiple LLVM versions installed from apt.llvm.org and pocl links to them without issues.

> I guess the default llvm-config --ldflags

the linking of libOpenCL doesn't depend on output of `llvm-config --ldflags`; pocl supports linking to libOpenCL.so with non-LLVM builds too.

But we should definitely fix the CMake llvm-config search names, because llvm-config dropped the ".0" versioning in ubuntu since LLVM 7; now it's just `llvm-config-N`.

**Comment by pjaaskel** [comment]
It is an ld.so linker path, but seems linker did not find it before I added a symlink to /usr/lib, so perhaps ld does not search from there by default. But this was not my system. It was a fresh Ubuntu 18.04 install though.

**Comment by sunfic** [comment]
1) check the configuration files under `/etc/ld.so.conf.d`.  your `/usr/lib/x86_64-linux-gnu` or `/usr/lib/aarch64-linux-gnu` or similar should be there to be found by CMake.
2) possible you don't have simlink `libOpenCL.so` file there but only `libOpenCL.so.1.0.0`. you need simlink it by yourself or install `ocl-icd-opencl-dev` package. it will create simlink for you.
