### ISSUE TITLE
runtime/clGetDeviceInfo fails on Debian kFreeBSD/i386

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#769]
From https://buildd.debian.org/status/fetch.php?pkg=pocl&arch=kfreebsd-i386&ver=1.3-6&stamp=1568489624&raw=0:
```
        Start  87: runtime/clGetDeviceInfo
 55/145 Test  #87: runtime/clGetDeviceInfo .............................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.02 sec
CMake Error at /<<PKGBUILDDIR>>/cmake/run_test.cmake:34 (message):
  FAIL: Test exited with nonzero code (1):
  /<<PKGBUILDDIR>>/obj-i686-kfreebsd-gnu/tests/runtime/test_clGetDeviceInfo


  STDOUT:

  

  STDERR:

  Assertion:

  max_mem_alloc_size >= min_max_mem_alloc_size

  failed on
  /<<PKGBUILDDIR>>/tests/runtime/test_clGetDeviceInfo.c:49



-- OK

```
Compare this to a Debian Linux/i386 build:
https://buildd.debian.org/status/fetch.php?pkg=pocl&arch=i386&ver=1.3-6&stamp=1568493901&raw=0

Since I also run `clinfo` as part of the tests, I'm showing parts of the clinfo diff between the two platforms:

```
@@ -175,16 +175,16 @@
     IEEE754-2008 fused multiply-add               Yes
     Support is emulated in software               No
   Address bits                                    32, Little-Endian
-  Global memory size                              3053217792 (2.844GiB)
+  Global memory size                              3195651072 (2.976GiB)
   Error Correction support                        No
-  Max memory allocation                           1073741824 (1024MiB)
+  Max memory allocation                           536870912 (512MiB)
   Unified memory for Host and Device              Yes
   Minimum alignment for any data type             128 bytes
   Alignment of base address                       1024 bits (128 bytes)
   Global Memory cache type                        None
   Image support                                   Yes
     Max number of samplers per kernel             16
-    Max size for 1D images from buffer            67108864 pixels
+    Max size for 1D images from buffer            33554432 pixels
     Max 1D or 2D image array size                 2048 images
     Max 2D image size                             8192x8192 pixels
     Max 3D image size                             2048x2048x2048 pixels
```
The full `clinfo` output is included in the two buildlogs.

The code leading to this assertion:
```
...
      err = clGetDeviceInfo(devices[j], CL_DEVICE_MAX_MEM_ALLOC_SIZE,
                            sizeof(max_mem_alloc_size), &max_mem_alloc_size,
                            NULL);
...
      min_max_mem_alloc_size = 128*1024*1024;
      if (min_max_mem_alloc_size < global_memsize/4)
        min_max_mem_alloc_size = global_memsize/4;

      TEST_ASSERT(max_mem_alloc_size >= min_max_mem_alloc_size);
...
```

Is `global_memsize/4` an arbitrary size or mandated by the standard?

Debugging is a bit difficult, since cmake is uninstallable in a porterbox kfreebsd-i386 chroot.

**Comment by Oblomov** [comment]
Hello Andreas,

>
> Is global_memsize/4 an arbitrary size or mandated by the standard?
>

This is mandated by the standard. The maximum memory allocation must
be _at least_ max(1/4th of all the global memory, 128MiB). So the
question is: why is the max alloc size only 512MiB on a 3GiB system?
pocl gets its allocation limits from getrlimit(RLIMIT_DATA).
(lib/CL/devices/common.c, find alloc_limit within
pocl_setup_device_for_system_memory). Does the BSD kernel put a
constraint on how large a single allocation can be? Or maybe this
specific system is otherwise configured to limit allocations so?

-- 
Giuseppe "Oblomov" Bilotta

**Comment by franz** [comment]
This may be also triggered by FreeBSD returning a very large RLIMIT_DATA and a bug in pocl. The bug is with mixing `size_t/cl_ulong` on 32bit systems, when a `cl_ulong` is passed to `pocl_size_ceil2()` [here](https://github.com/pocl/pocl/blob/3d5f25ecc041f2c7dfc75c52628c0bb08e46eb43/lib/CL/devices/common.c#L1183). I've run into the same [problem recently](https://github.com/pocl/pocl/pull/768/commits/6551002185e5fe14c3c2827e000d268250c4aeb6) - that patch doesn't apply to current code but i can backport it.

**Comment by anbe42** [comment]
I tried a backported version of the patch in my recent 1.3-7 upload to Debian/sid:
https://salsa.debian.org/opencl-team/pocl/blob/master/debian/patches/0001-Fix-a-bug-on-32bit-systems.patch
but it didn't change anything:
i386: https://buildd.debian.org/status/fetch.php?pkg=pocl&arch=i386&ver=1.3-7&stamp=1569283139&raw=0
kfreebsd-i386: https://buildd.debian.org/status/fetch.php?pkg=pocl&arch=kfreebsd-i386&ver=1.3-7&stamp=1569284958&raw=0

There are two more occurrences of `pocl_size_ceil2()` with `cl_ulong` arguments (at least in 1.3):
```
./lib/CL/devices/common.c:    s = pocl_size_ceil2 (device->global_mem_cache_size / 2);
./lib/CL/devices/common.c:    s = pocl_size_ceil2 (device->global_mem_size / 256);
```

**Comment by franz** [comment]
Should be fixed in both master & release_1_4. Please retest

**Comment by pjaaskel** [comment]
Assuming fixed. Please reopen if not.
