### ISSUE TITLE
allocates 256 MB local memory per thread

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#810]
The pocl pthread device allocates 16 MB printf buffer and 256 MB local memory per thread.
This can quickly exhaust memory on 32-bit platforms (less than 4 GB address space) with moderate core counts - a 8-core cpu with hyperthreading causes creation of 16 threads, resulting in a crash.

**Comment by pjaaskel** [comment]
Intel's OpenCL SDK seems to allocate only 32KiB for local mem (matches my L1d size), so indeed 250MB sounds a bit overkill. Perhaps we could set it to 1MB for pthread or to the L2 cache size or such. Should be an easy change, just fetch the info from hwloc. Can you fix this and send a PR?

**Comment by pjaaskel** [comment]
A logical value would be the largest HW thread / core dedicated cache size (in this laptop's CPU case it's the L2, 256 KiB for example) but setting it to L2 without considering locality should be fine too.

**Comment by anbe42** [comment]
The CPU in this box is an i7-9800X with 16 MB L3.
`lib/CL/devices/common.c` `pocl_set_buffer_image_limits()` sets `device->local_mem_size` to 16 MB (that's probably the point where you suggested to fix it):
```
  if (device->global_mem_cache_size > 0)
    s = pocl_size_ceil2_64 (device->global_mem_cache_size / 2);
  else
    s = pocl_size_ceil2_64 (device->global_mem_size / 256);
  device->local_mem_size = device->max_constant_buffer_size = s;
 ```
based on values gained by `lib/CL/devices/topology/pocl_topology.c` `pocl_topology_detect_device_info()`
but `lib/CL/devices/pthread/pthread_scheduler.c` `pthread_scheduler_init()` blows it up by a factor of 16 (part of the problem):
```
  /* safety margin - aligning pointers later (in kernel arg setup)
   * may require more local memory than actual local mem size.
   * TODO fix this */
  scheduler.local_mem_size = device->local_mem_size << 4;
```
And then this amount is allocated by each worker thread (another part of the problem).
(There is also a 16 MB printf buffer per worker thread, which is marginal compared to the overestimated local memory.)

**Comment by pjaaskel** [comment]
The L3 is likely shared across cores, right? I meant to use the size of the largest cache that is dedicated for a thread/core, it makes the most sense in this context since local mem and WGs are executed per thread/core. 

Multiplying the local mem by 16 there simply doesn't make sense and is overkill for the purpose mentioned in the comment. The overhead amount should be a constant amount calculated from the max number of arguments we can push in the kernel call instead of such a huge margin. I think the TODO there is correct :)

**Comment by franz** [comment]
> I meant to use the size of the largest cache that is dedicated for a thread/core, it makes the most sense in this context since local mem and WGs are executed per thread/core.

+1

> The overhead amount should be a constant amount

perhaps `device->max_parameter_size` * largest alignment (128 ?) could work

> Multiplying the local mem by 16 there simply doesn't make sense and is overkill 

True, OTOH it never was a problem on 64bit systems, since the only thing wasted is a bit of virtual AS.

Also both the printf buffer and local mem size (since we support builds without hwloc) could have optional CMake variables that would be hardcoded into libpocl.

**Comment by anbe42** [comment]
I've now tried
```
-  scheduler.local_mem_size = device->local_mem_size << 4;
+  scheduler.local_mem_size = device->local_mem_size + device->max_parameter_size * MAX_EXTENDED_ALIGNMENT;
```
which reduces the safety margin from 240 MB to 128 KB. That works for me now, but with 18 core (36 threads, 24.75 MB L3) CPUs available on the market today, there is probably only growth by a factor of 2 covered before we run into similar problems, again.

**Comment by Oblomov** [comment]
A ThreadRipper 3990X has 64 cores, 128 threads, 4MiB L1 cache total, 32MiB L2 cache total and 256MiB L3 cache total. But then again, how much sense does it make to use 32-bit addressing (or less than 4GiB of RAM in general) with such a monster CPU? There's only so much things can be optimized for such extreme setups without negatively affecting more common use cases.

(That being said, restricting the local memory size to the L3, or even a closer, cache makes a lot of sense, and I would argue the change should have been made even without the issue of excessive memory consumption.)

**Comment by pjaaskel** [comment]
Yes.

**Comment by new2f7** [comment]
I've stumbled upon the code in `lib/CL/devices/common.c` cited by anbe42 above, too. I'm a wee bit confused about the fixed divisor of `256`. How about CPUs that have more than 256 hardware threads? When the divisor [has been changed](https://github.com/pocl/pocl/commit/2541188fd42fd29fb2d443280de9b97a198b55e0) from `4` to `256`, the related source code comment hasn't been updated. Shouldn't `device->global_mem_size` be divided by the number of hardware threads (and maybe an additional fixed configurable factor to not treat the whole global memory as potential local memory)?

Furthermore, if I correctly understand [pocl_topology.c](https://github.com/pocl/pocl/blob/master/lib/CL/devices/topology/pocl_topology.c), it will detect the L2 cache size per core on most CPUs. Thus, it is reasonable to divide `device->global_mem_cache_size` by `2` if hyper-threading is enabled. What if hyper-threading is disabled (like on some HPC systems)? Shouldn't `device->global_mem_cache_size` be divided by `2` only if hyper-threading is enabled?

In case you agree on these proposed changes, I'll may supply the corresponding patch.

**Comment by franz** [comment]
> Shouldn't device->global_mem_size be divided by the number of hardware threads 

Yeah it would be a better approach to divide by `number of threads * some-constant`. 

> (and maybe an additional fixed configurable factor to not treat the whole global memory as potential local memory)?

IMO better to have configurable value for final local memory size (= not for a factor in its calculation).

> Shouldn't device->global_mem_cache_size be divided by 2 only if hyper-threading is enabled?

Yeah, ATM it's not because nobody has been interested enough. If you want to add HT support into `pocl_topology.c`, we would certainly consider a patch.

If pocl can't get the L2 size numbers in a reliable way (= `hwloc`, or `/proc`), it's forced to wildly guess (which is what this code does). We can tune the guessing code to infinity, but unlike in GPUs which have actual dedicated local memory with fixed-size, in CPU case, over-estimating doesn't seem to affect a lot of people (except for issues like this bug - overallocation).

Another perfectly valid approach would be to 1) use hwloc / proc, 2) avoid any guesswork, instead fallback to a value from a CMake option, with its default being some small fixed number (128K for example). I *suspect* most OpenCL algorithms are tuned for real-world GPUs, which have a certain ratio of (local memory size / max items in WG), and since pocl's max-items-in-WG is fixed, we might also have a fixed default fallback for local memory size, as long as we keep that ratio.

**Comment by pjaaskel** [comment]
Sounds pretty reasonable to me also. I'd try primiarly the 1) and use a hwloc to find a reasonable cache level to use for the local memory (a level mostly dedicated for a HW thread) also have 2) a reasonable static fallback for the CPU devices. But heavily attempt 1) because pocl should port across CPUs after compilation too (we should support binary distribution mode well too and CPU upgrades).

pocl's CPU max-items-in-WG should be in general SIZE_T_MAX, but I suppose it's fixed to lower than that to avoid exploding the private memory consumption since some programs (also some in the CTS) do not check for the private memory usage, and just  blindly max out the WI count for a reason or another which can lead to OOM (right Michal?).

**Comment by Oblomov** [comment]
I've given a look at what the other CPU platforms report, and it seems to be a bit inconsistent wrt to cache and local memory size However, both Intel and AMD (fglrx) stick to core-specific caches. To report cache information, Intel uses the highest-level core-specific cache (on this machine: L2, 256KiB), whereas AMD uses the lowest-level core-specific cache (on this machine: L1d, 32Kib). The reported information is per-core.

For local memory, both Intel and AMD (fglrx) report the L1d cache size (32KiB). I think this makes sense, since local memory is supposed to be fast on-chip memory, and spilling out of the L1 kind-of defeats this.

I think this also means that having arbitrarily large work-group size has no benefit (outside of the potential OOM issue): ideally, all of the work-items' private and work-group's local storage should fit as closely as possible to the compute core, which means we should not really spill out of registers and L1 or at most L2 cache. I honestly think that the 4K local work-size is a good hotspot (by comparison: Intel reports 8K, AMD fglrx was limited to 1K), but we might want to consider tuning it up or down based on vector capabilities of the hardware.

**Comment by pjaaskel** [comment]
Thanks for the analysis. Yes, you are likely right that arbitrarly large WG size has rarely benefits. I see the benefits mainly in the kernels which do not use local mem (thus are likely embarrasingly parallel) and then it might reduce the number of work-group function launches and its associated overheads, but it's likely a negligible benefit and a rare case.

**Comment by Oblomov** [comment]
Without local memory usage, there's arguably still the issue of register pressure and cache efficiency to keep in mind: a problem might be embarrassingly parallel, but requires several registers for processing, which might lead to spilling, in which case we want the spills to fit in cache (if possible).

If launch overhead starts to become significant, and there is no collaboration between work-items in a work-group, wouldn't it be possible for pocl to just merge the work-groups internally? Under these circumstances such a fusion (resulting in local sizes potentially even larger than advertised to the user) would be transparent to the user, I think.

**Comment by pjaaskel** [comment]
The work-item context data (private variables) is pretty much the same problem (the private variables might be stored in registers or memory via spills, and private arrays are typically in mem unless scalarized), but even with them it's less a problem when there are no barriers to maintain their state over: If there are no barriers, the WIs are just looped over (hopefully loop vectorized too!) and if there is only a single parallel region loop, it means the live ranges of the private variables does not span outside the single WI loop body -> register pressure doesn't grow with the WI count. 

Like said, the launch overhead is likely never significant as such with any reasonable WI counts, at least when we get the WG task scheduler code streamlined.
