### ISSUE TITLE
Memory consumption issue with device maps

### ISSUE THREAD

**Issue by tbetcke** [pocl/pocl#812]
Hi,

I noticed a strange behavior with device maps. A short example C++ code is given at:

https://gist.github.com/tbetcke/ff3c62b06685e5d8817b7b0c88a91642

Within a for-loop I am creating buffers and then use a device map to fill them. Each buffer takes around 2Mb in memory and should be deleted automatically at the end of the for loop. When I run the code with only one loop iteration the program takes around 30 MB in peak Ram. However, when I run it with 100 iterations it takes around 180MB Ram.  This is a simplified example from a production code, where this phenomenon leads to a code requiring gigabytes of Ram.

I am compiling with

g++ -o test_cl test_cl.cpp -lOpenCL

and run the code with

/usr/bin/time -v test_cl

to measure peak memory consumption.

I tested it with the current pocl master branch and LLVM 6 from Ubuntu 18.04 LTS. Valgrind does not show any memory leakage issues. But the memory consumption causes us serious problems in productionc codes.

It would be great to get to the source of this issue.
Thanks

Timo

**Comment by franz** [comment]
I think this assumption is wrong:

> Each buffer takes around 2Mb in memory and should be deleted automatically at the end of the for loop

You delete the C++ object, which calls `clReleaseMemObj` - but OpenCL objects are reference counted. Everytime you enqueue a command, Pocl increases the refcount of all memory objects it uses, and the refcounts are decreased only when the CPU driver threads (which run asynchronously) are done executing those commands. So deleting C++ objects doesn't mean buffer is released; it's released when the refcount drops to zero. Which will be much later, if you enqueue commands faster than the driver can process them - and you will see "memory leak" which valgrind won't report since it's not really a leak.

Your loop, from synchronization POV, looks like this:
1) clEnqueueUnmap(previous buffer, don't synchronize)
2) clCreateBuffer(new buffer)
3) clEnqueueMap(new buffer, synchronize)

At point 3) the driver waits for execution of both enqueued commands, so at any time, you will have at most 2 buffers "alive". If you add a clFinish after Unmap, the deleting of C++ object (clReleaseMemObj) at loop end will actually release the memory at that point, and you'll only have 1 buffer "alive" at any time.

> When I run the code with only one loop iteration the program takes around 30 MB in peak Ram. However, when I run it with 100 iterations it takes around 180MB Ram

This is probably because you have a multicore CPU, and some per-core memory structs in the CPU driver don't get initialized for other CPU cores, if you run just 1 command. Try running significantly more iterations than you have CPU cores. I have run your loop 20k times and watched the memory usage in top - it's somewhat random but completely steady.

**Comment by tbetcke** [comment]
Dear Michal,

thanks for the very comprehensive response. This helps a lot. I will close the bug report for now. Thanks again for this great project.

Timo
