### ISSUE TITLE
A question about scheduling

### ISSUE THREAD

**Issue by new2f7** [pocl/pocl#813]
I recently [had a look](https://github.com/pocl/pocl/pull/808) at pocl's strategy of scheduling work groups to threads. The current strategy takes the number of remaining work groups into account and divides that number by the number of threads.

Hence, scheduling 16 work groups onto 4 threads may looks like this (max_wgs is the number of work groups to be execute by the thread):
```
[Thread #1] remaning_wgs=16 => max_wgs=4
[Thread #2] remaning_wgs=12 => max_wgs=3
[Thread #3] remaning_wgs=9 => max_wgs=3
[Thread #4] remaning_wgs=6 => max_wgs=2
[Thread #4] remaning_wgs=4 => max_wgs=1
[Thread #2] remaning_wgs=3 => max_wgs=1
[Thread #3] remaning_wgs=2 => max_wgs=1
[Thread #4] remaning_wgs=1 => max_wgs=1
```
Note that in the above example Thread 1 polls work groups once, while Thread 4 polls work groups 3 times.

This strategy roughly corresponds to the `guided` strategy of [OpenMP](https://www.openmp.org/spec-html/5.0/openmpsu41.html#x64-1290002.9.2). Obvious drawbacks are potential unnecessary scheduling overhead (when comparing to static scheduling) or (when having imbalanced work in work groups) relying on the first work groups to have less work than the others.

I'm aware of the discussion in [issue 330](https://github.com/pocl/pocl/issues/330).

**Could someone recall the reasons why this scheduling strategy has been chosen?** I'd be grateful for any comments that can clarify my confusion.

**Comment by franz** [comment]
I can't comment on the original reasoning, but my wild guess is: because "pull" model has certain (maybe less obvious) advantages. In particular, static scheduling can be result in higher total execution time, even though it has less scheduling overhead.

**Comment by pjaaskel** [comment]
I have some experimental unfinshed code that should improve the work-group distribution and load-balancing. It also reduces locking since I made it to improve latency critical codes. I can push it if you want to take a look and perhaps polish it to something mergeable.

**Comment by pjaaskel** [comment]
FWIW, https://github.com/parmance/pocl/tree/pthread-wg-balancing-optimizations here it is. The WG work sharing concept should make some sense, and it now uses a single atomic updated index instead of a longish critical section, but I didn't have the time to finish the work queue spinning code so it now leads to heavy lock thrashing when there are lots of worker threads pounding the work queue lock. It leads to starvation quickly (due to the app thread not being able to add work to the queue due to the locks held by the hungry workers).

The work-group sharing's idea is to always distribute at most about half of the remaining WGs to the workers.  Based on the quick tests it seemed to improve the current work sharing a lot with regards to calls to the WG sharing function and resulting load balance (even in presence of other background threads slowing some of the WGs down), but my tests were limited in terms of applications and multicores.

So feel free to check if it makes any more sense for your benchmark of interest and pick it up if you want.
