### ISSUE TITLE
CUDA: constant size local memory is allocated as dynamic shared memory

### ISSUE THREAD

**Issue by isuruf** [pocl/pocl#823]
If I compile the following kernel using POCL and inspect the PTX, the OpenCL local memory is declared extern (dynamic shared memory in CUDA). If I compile the kernel with the same clang version (9.0.1) using `clang -x cl -S kernel.cl -o kernel.ptx --target=nvptx64-unknown-unknown  -Xclang -finclude-default-header`, then the local memory is declared as static shared memory in CUDA. The dynamic shared memory kernel is slow as it leads to lesser optimization opportunities.

cc @nchristensen, @inducer, @jrprice 

```OpenCL
#define lid(N) ((int) get_local_id(N))
#define gid(N) ((int) get_group_id(N))

__kernel void __attribute__ ((reqd_work_group_size(32, 32, 1))) diff(__global float *__restrict__ result, __global float const *__restrict__ mat, __global float const *__restrict__ vec)
{
    float acc_j;
    __local float matf[32 * 32];
    __local float vecf[32 * 32];

    vecf[32 * lid(1) + lid(0)] = vec[1048576 * lid(1) + 32 * gid(0) + lid(0)];
    matf[32 * lid(1) + lid(0)] = mat[32 * lid(1) + lid(0)];
    acc_j = 0.0f;
    barrier(CLK_LOCAL_MEM_FENCE)
    /* for matf (insn_j_update depends on mat_fetch_rule) */;
    for (int j = 0; j <= 31; ++j)
        acc_j = acc_j + matf[32 * lid(1) + j] * vecf[32 * j + lid(0)];
    result[1048576 * lid(1) + 32 * gid(0) + lid(0)] = acc_j;
}
```

**Comment by pjaaskel** [comment]
You might want to check the 'device_alloca_locals' and 'autolocals_to_args' device driver configuration parameters. The relevant kernel compiler files are Workgroup.cc and AutomaticLocals. There are different ways local memory can be implemented in the POCL framework and it already supports a few by just tuning these options.

**Comment by jrprice** [comment]
It's been a while since I looked at this stuff, so I can't remember all the details. The pocl CUDA backend does a transformation to squash all local memory arguments and static allocations into a single extern `__shared__` variable:
https://github.com/pocl/pocl/blob/master/lib/CL/devices/cuda/pocl-ptx-gen.cc#L711

The comment indicates that the reason is because CUDA variant of PTX does not allow more than one shared memory allocation/argument (I believe CUDA and OpenCL have different ideas about what is valid in PTX). It's possible that I was mistaken about this, so it's worth trying to see if you can get CUDA to consume PTX with multiple shared memory allocations if you think this should work.

**Comment by isuruf** [comment]
After some debugging, it turns out that it's not https://github.com/pocl/pocl/blob/master/lib/CL/devices/cuda/pocl-ptx-gen.cc#L711 . It's `AutomaticLocals.cc` as @pjaaskel mentioned which turns the local declaration inside the kernel into arguments. How can I turn off this pass just for CUDA?

**Comment by isuruf** [comment]
Nevermind. Read @pjaaskel's comment again. Thanks

**Comment by isuruf** [comment]
I think we'll have to differentiate the two cases. Let's call __local in function arguments A and __local declarations inside the kernel B.

If A is there we must turn on `autolocals_to_args`.
If there's only B, we can turn off `autolocals_to_args`.
