### ISSUE TITLE
"pocl_read_file" function execution time inside "pocl_llvm_build_program" function is variable

### ISSUE THREAD

**Issue by andouwa** [pocl/pocl#861]
this should not be an issue, but a performance concern, we found that "pocl_read_file" function execution time is not stable, sometimes 2 times than normal, how should we handle this?

**Comment by andouwa** [comment]
I think this unstable execution time is as expected, since it need to read file from disk.
in pocl document, it says “Note that it’s currently not possible for pocl to avoid interacting with LLVM via on-disk files, so pocl requires some disk space at least temporarily (at runtime).”
so to make the execution time more stable, is it possible to avoid the avoid interacting with LLVM via on-disk files?

**Comment by pjaaskel** [comment]
The cache dir is needed even if caching would be disabled since not all steps of the kernel compilation are yet done in memory (it would require calling the linker via API calls and load the program using the LLVM JIT APIs instead of dlopen), and the preprocessed source is used to generate a unique hash for the program's cache dir. I think someone outside our group was working on improving this, but I cannot recall who.

**Comment by andouwa** [comment]
> The cache dir is needed even if caching would be disabled since not all steps of the kernel compilation are yet done in memory (it would require calling the linker via API calls and load the program using the LLVM JIT APIs instead of dlopen), and the preprocessed source is used to generate a unique hash for the program's cache dir. I think someone outside our group was working on improving this, but I cannot recall who.

thanks a lot for your clarification.
