### ISSUE TITLE
Loop unrolling disabled for CUDA when using LLVM 11

### ISSUE THREAD

**Issue by nchristensen** [pocl/pocl#932]
Moving from LLVM 9 to LLVM 11 on pocl 1.6 we observed a performance regression on matrix multiplication kernels running on an Nvidia GPU (see https://github.com/illinois-ceesd/mirgecom/issues/295). It appears LLVM 11 inserts `.pragma "nounroll";` into the PTX whereas LLVM 9 performs unrolling. Happily, flipping `cg.UnrollLoops` [here](https://github.com/pocl/pocl/blob/4f3f90809c46d0277de8ef47c38a9dbae218837b/lib/CL/pocl_llvm_build.cc#L511) seems to re-enable loop unrolling. What would be the best way to keep loop unrolling enabled for the CUDA target on LLVM 11? Should `cg.UnrollLoops` be set to true by default?

cc @inducer, @matthiasdiener, @isuruf

**Comment by isuruf** [comment]
Something like below should work. Can you confirm?
```
diff --git a/lib/CL/pocl_llvm_build.cc b/lib/CL/pocl_llvm_build.cc
index 1fb838b4..630a3916 100644
--- a/lib/CL/pocl_llvm_build.cc
+++ b/lib/CL/pocl_llvm_build.cc
@@ -506,12 +506,18 @@ int pocl_llvm_build_program(cl_program program,
   CodeGenOptions &cg = pocl_build.getCodeGenOpts();
   cg.EmitOpenCLArgMetadata = true;
   cg.StackRealignment = true;
-  // Let the vectorizer or another optimization pass unroll the loops,
-  // in case it sees beneficial.
-  cg.UnrollLoops = false;
-  // Lets leave vectorization to later compilation phase
-  cg.VectorizeLoop = false;
-  cg.VectorizeSLP = false;
+  if (!device->spmd) {
+    // Let the vectorizer or another optimization pass unroll the loops,
+    // in case it sees beneficial.
+    cg.UnrollLoops = false;
+    // Lets leave vectorization to later compilation phase
+    cg.VectorizeLoop = false;
+    cg.VectorizeSLP = false;
+  } else {
+    cg.UnrollLoops = true;
+    cg.VectorizeLoop = true;
+    cg.VectorizeSLP = true;
+  }
   cg.VerifyModule = true;
 
   PreprocessorOutputOptions &poo = pocl_build.getPreprocessorOutputOpts();
```

**Comment by inducer** [comment]
```
+    cg.VectorizeLoop = true;
+    cg.VectorizeSLP = true;
```
I'm not sure vectorization is helpful for the PTX target.

**Comment by Oblomov** [comment]
IME 2-way vectorization almost always helps, due to a combination of improved memory bandwidth usage and exploitation of ILP. This was particularly evident on NVIDIA architectures with odd/even dual dispatch (2.1, 3.x), but it's still practical in many cases and in more recent architectures. 4-way vectorization can also help, although the benefits are usually less than from scalar to 2-way.

**Comment by inducer** [comment]
I agree that instruction-level parallelism helps! But is that what the vectorizer would produce in this case?

**Comment by pjaaskel** [comment]
Coming to think of this, I wonder why we are poking with Clang/LLVM defaults the first place here? Shouldn't Clang/LLVM know what are the best default optimizations to do per target. Especially with the SPMD target PoCL should do very little since we won't do WG vectorization.

**Comment by pjaaskel** [comment]
...which brings the question: _Should_ we do WG vectorization to utilize the ILP in the NVIDIA GPU targets? I'm not familiar enough with the (micro)architectures to know. We did an experiment like that with the old AMD VLIW-based GPU targets to expose more (cross-WI) ILP with the kernel compiler before PoCL was started (10+ years ago) from that and indeed it was helpful and could bring 2x speedups in some cases, IIRC.

**Comment by Oblomov** [comment]
TeraScale was infamous for being absolutely deficient without vectorization, I'm surprised the most you would see was 2x speedup (but I guess this could have been a limit with automatic vectorization).

With NVIDIA the situation is extremely volatile, in the sense that it largely depends on the major and sometimes even the _minor_ revision of the architecture (e.g. Fermi 2.0 was single-issue, but 2.1 was odd/even dual issue; Kepler 3.x was all odd/even dual issue; from Pascal onwards, the situation is even more complex because sometimes the consumer and the pro/compute cards are widly different).

As a general rule, as I mentioned above, on NVIDIA the largest impact of vectorization actually comes from improved memory utilization (using float vs float2 on memory-bound kernels can give close to a 2x speed-up on memory-bound and esp. memory-only kernels), even on archs without a meaningful (documented) ILP. ILP also helps, but the effect is usually less impressive, so we might not want to waste time with it, and let the user do things manually.

Another option could be to base the vectorization for each kernel on the basis of the `vec_type_hint()` attribute. This could also be used as a way to let the user specify that a particular kernel should _not_ be vectorized (IIRC Intel's platform does or used to do something like that for its CPU compiler).

**Comment by pjaaskel** [comment]
Yep, it could have been we only tried 2-way work-item replication, and it could have been more. Note, not vectorization but VLIW ILP (multi-issue) on the lane, IIRC.

I leave it up to those familiar with the NVIDIA variants to figure the best way out, but sounds to me it's too early to remove the original 'repl' work-group function method from PoCL, which I planned to do Soon ;)

**Comment by inducer** [comment]
I agree with @pjaaskel that it's probably best to leave the Clang/LLVM defaults in place for SPMD devices, until there's a specific reason to change them.

**Comment by Oblomov** [comment]
I think it's a good idea too. As a bonus, it's consistent with what NVIDIA does (meaning less things to look for in case of performance regressions —vectorization _can_ impact things negatively, as I've experienced with Intel's vectorizer).

**Comment by nchristensen** [comment]
@isuruf Yes, that seems to re-enable loop unrolling for Nvidia.
